export const AnalyticsEventTypes = {
  SCAN: "SCAN",
  SESSION_START: "SESSION_START",
  SESSION_END: "SESSION_END",
  FLOW_START: "FLOW_START",
  FLOW_STEP: "FLOW_STEP",
  FLOW_COMPLETE: "FLOW_COMPLETE",
  FLOW_ABANDON: "FLOW_ABANDON",
  FLOW_TRIGGERED: "FLOW_TRIGGERED",
  AI_MEMORY_USED: "AI_MEMORY_USED",
  AI_MEMORY_LEARNED: "AI_MEMORY_LEARNED",
  AI_MEMORY_RECOMMENDED: "AI_MEMORY_RECOMMENDED",
  AI_CREATIVE_ACCEPTED: "AI_CREATIVE_ACCEPTED",
  AI_CREATIVE_REJECTED: "AI_CREATIVE_REJECTED",
  AI_VARIATION_SELECTED: "AI_VARIATION_SELECTED",
  AI_SIGNIFICANCE_SHIFT: "AI_SIGNIFICANCE_SHIFT",
  AI_CINEMATIC_DECISION: "AI_CINEMATIC_DECISION",
  AI_DECISION: "AI_DECISION",
  MEMORY_APPLIED: "MEMORY_APPLIED",
  MEMORY_CREATED: "MEMORY_CREATED",
  MEMORY_UPDATED: "MEMORY_UPDATED",
  MEMORY_RECOMMENDATION_VIEWED: "MEMORY_RECOMMENDATION_VIEWED",
  MEMORY_RECOMMENDATION_SELECTED: "MEMORY_RECOMMENDATION_SELECTED",
  SPONSOR_IMPRESSION: "SPONSOR_IMPRESSION",
  SPONSOR_INTERACTION: "SPONSOR_INTERACTION",
  SPONSOR_DISMISSED: "SPONSOR_DISMISSED",
  SPONSOR_CTA_CLICK: "SPONSOR_CTA_CLICK",
  CTA_CLICK: "CTA_CLICK",
  REDIRECT: "REDIRECT",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_STARTED: "PAYMENT_STARTED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  UNLOCK: "UNLOCK",
  CLAIM_STARTED: "CLAIM_STARTED",
  CLAIM_COMPLETED: "CLAIM_COMPLETED",
  TEASER_VIEW: "TEASER_VIEW",
  GEO_MARK: "GEO_MARK",
  WEBSITE_CLICK: "WEBSITE_CLICK",
  SOCIAL_CLICK: "SOCIAL_CLICK",
  TIP_STARTED: "TIP_STARTED",
  TIP_COMPLETED: "TIP_COMPLETED",
  ERROR: "ERROR",
  FLOW_POLICY_APPLIED: "FLOW_POLICY_APPLIED",
  CHECK_IN: "CHECK_IN",
  CHECK_OUT: "CHECK_OUT",
  PRESENCE_JOIN: "PRESENCE_JOIN",
  PRESENCE_LEAVE: "PRESENCE_LEAVE",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_VIEWED: "TICKET_VIEWED",
  TICKET_REDEEMED: "TICKET_REDEEMED",
  TICKET_REJECTED: "TICKET_REJECTED",
  MEDIA_PLAY: "MEDIA_PLAY",
  MEDIA_COMPLETE: "MEDIA_COMPLETE",
  MEDIA_REPLAY: "MEDIA_REPLAY",
  EXPERIENCE_REPLAY: "EXPERIENCE_REPLAY",
  EXPERIENCE_SHARED: "EXPERIENCE_SHARED",
  EXPERIENCE_SAVED: "EXPERIENCE_SAVED",
} as const;

export type AnalyticsEventType = (typeof AnalyticsEventTypes)[keyof typeof AnalyticsEventTypes];

export const AnalyticsLearningClasses = {
  FACTUAL_WORLD: "FACTUAL_WORLD",
  BEHAVIORAL_SIGNAL: "BEHAVIORAL_SIGNAL",
  CREATIVE_PREFERENCE: "CREATIVE_PREFERENCE",
  FRICTION_SIGNAL: "FRICTION_SIGNAL",
  MEMORY_SIGNAL: "MEMORY_SIGNAL",
  BUSINESS_SIGNAL: "BUSINESS_SIGNAL",
  RUNTIME_HEALTH: "RUNTIME_HEALTH",
  NON_LEARNING: "NON_LEARNING",
} as const;

export type AnalyticsLearningClass = (typeof AnalyticsLearningClasses)[keyof typeof AnalyticsLearningClasses];

export interface AnalyticsEventClassification {
  type: AnalyticsEventType;
  learningClass: AnalyticsLearningClass;
  feedsAuthor: boolean;
}

export interface AnalyticsEvent {
  type: AnalyticsEventType;
  createdAt: Date;
  assetId?: string;
  sessionId?: string;
  userId?: string;
  metadata?: Record<string, unknown>;
}
