import type { AuthorDomainContext, MouthBeamOptions, MouthCandidate, MouthCandidateBatch, MouthCandidateBeat, MouthCandidatePool, MouthSequencePath } from "@qre/contracts";
import type { RealityEnvelope } from "./authorRealityEnvelope.js";
import { classifyLens } from "./authorCharacterLensEngine.js";

/** ONE PRODUCTION MOUTH. Generation, authorization, and sequence selection live here. */
export type { MouthCandidateBeat } from "@qre/contracts";
export type MouthCandidateGenerationInput = { envelope: RealityEnvelope; beats: readonly MouthCandidateBeat[]; priorTexts?: readonly string[]; lens?: string; domainContext?: AuthorDomainContext };
const clean=(value:unknown)=>String(value??"").replace(/\s+/g," ").trim();
const metric=(value:number)=>Number(Math.max(0,Math.min(1,Number.isFinite(value)?value:0)).toFixed(3));
const STOP=new Set(["the","a","an","and","or","but","to","of","in","on","at","for","with","from","by","through","after","before","then","now","still","again","this","that","it","is","are","was","were","be","been","being","as","into","my","your","our","their","his","her","its","he","she","they","them","you","we","me","very","really","just","already","apparently","anyway","perhaps","maybe"]);
const tokens=(value:string)=>new Set(clean(value).toLowerCase().split(/[^a-z0-9'’-]+/g).filter(t=>t.length>=3));
const meaningful=(value:string)=>new Set([...tokens(value)].filter(t=>!STOP.has(t)));
const overlap=(a:Set<string>,b:Set<string>)=>{if(!a.size||!b.size)return 0;let h=0;for(const t of a)if(b.has(t))h++;return h/Math.max(1,a.size)};
const wordCount=(value:string)=>clean(value).split(/\s+/).filter(Boolean).length;
function sourceLabels(beat:MouthCandidateBeat,envelope:RealityEnvelope){return [...new Set((beat.eventIds??[]).map(id=>envelope.events.find(e=>e.id===id)?.label??"").map(clean).filter(Boolean))]}
function worldSource(envelope:RealityEnvelope){return [envelope.subject,...envelope.events.map(e=>e.label),...envelope.suppliedPhrases,...envelope.suppliedEntities,...envelope.suppliedActions,...envelope.suppliedStates,...envelope.recurringSignals,...envelope.sensorySignals,...envelope.unresolvedTensions].map(clean).filter(Boolean)}
function semanticSource(beat:MouthCandidateBeat){const s=beat.semanticRealization;if(!s)return [];const o=beat.observerExperience;return [s.subject,s.before,s.after,s.relation?.kind,s.callback?.detail,s.realizationMove,s.creativeOpportunity,s.mechanism,o?.objective,o?.surprise,o?.curiosity,o?.landing,...(o?.attention??[])].map(clean).filter(Boolean)}
function exactSource(text:string,labels:readonly string[]){const v=clean(text).replace(/[.!?]+$/g,"").toLowerCase();return labels.some(l=>clean(l).replace(/[.!?]+$/g,"").toLowerCase()===v)}
function concreteRisk(text:string,source:string){const v=clean(text);if(!v)return 1;if(/\b(?:qre|cognition|planner|planning|candidate|semantic|trajectory|viewer|observer|objective|audience|mouth|author|beam|payoff\s+dependency)\b/i.test(v))return 1;if(/\b(?:this means|which means|the meaning is|the point is|the viewer|the audience|this proves|in other words)\b/i.test(v))return 1;const c=meaningful(v),s=meaningful(source),ov=overlap(c,s);const unsupported=/\b(?:walk(?:ed|s)?|run(?:ning|s)?|jump(?:ed|s|ing)?|grab(?:bed|s|bing)?|kiss(?:ed|es|ing)?|hug(?:ged|s|ging)?|smil(?:ed|es|ing)?|laugh(?:ed|s|ing)?|talk(?:ed|s|ing)?|open(?:ed|s|ing)?|clos(?:ed|es|ing)?|enter(?:ed|s|ing)?|return(?:ed|s|ing)?|watch(?:ed|es|ing)?|look(?:ed|es|ing)?|move(?:d|s|ing)?|touch(?:ed|es|ing)?|throw|threw|catch|caught|dance(?:d|s|ing)?|drive|drove|push(?:ed|es|ing)?|pull(?:ed|s|ing)?|vanish(?:ed|es|ing)?|disappear(?:ed|es|ing)?)\b/i.test(v);return unsupported&&ov<0.55?1:0}
function semanticAuthorization(text:string,beat:MouthCandidateBeat,envelope:RealityEnvelope){const s=beat.semanticRealization;if(!s)return{authorized:false,strength:0};const evidence=new Set(s.evidenceEventIds??[]),eventIds=beat.eventIds??[];const c=meaningful(text),labels=sourceLabels(beat,envelope),st=meaningful(semanticSource(beat).join(" "));const before=meaningful(clean(s.before)),after=meaningful(clean(s.after));const ba=overlap(c,before),aa=overlap(c,after),so=overlap(c,st);const sourceCoverage=labels.filter(l=>overlap(meaningful(l),c)>=0.5).length;const cross=sourceCoverage>=2;const beforeAfter=before.size>0&&after.size>0&&ba>=0.18&&aa>=0.18;const move=so>=0.34;const anchorIds=uniqueStrings([...(s.beforeEventIds??[]),...(s.afterEventIds??[])]);const anchorPositions=anchorIds.map(id=>envelope.events.findIndex(e=>e.id===id));const allAnchorsResolve=anchorIds.length>=2&&anchorPositions.every(i=>i>=0);const minAnchor=allAnchorsResolve?Math.min(...anchorPositions):-1;const maxAnchor=allAnchorsResolve?Math.max(...anchorPositions):-1;const bridgeEvent=allAnchorsResolve&&minAnchor<maxAnchor&&eventIds.some(id=>{const p=envelope.events.findIndex(e=>e.id===id);return p>minAnchor&&p<maxAnchor});const bridgeGrounded=bridgeEvent&&labels.some(label=>overlap(c,meaningful(label))>=0.18);const bridgeSpanApproved=bridgeEvent&&[...evidence].every(id=>anchorIds.includes(id));const bridge=Boolean(bridgeSpanApproved&&bridgeGrounded);const implied=beforeAfter||cross||move||bridge;if(!implied)return{authorized:false,strength:0};return{authorized:true,strength:metric((beforeAfter?0.45:0)+(cross?0.3:0)+(move?0.25:0)+(bridge?0.12:0))}}
function uniqueStrings(values:readonly string[]):string[]{return [...new Set(values.map(clean).filter(Boolean))]}
function evaluateCandidate(text:string,beat:MouthCandidateBeat,envelope:RealityEnvelope,priorTexts:readonly string[]):MouthCandidate{const v=clean(text),labels=sourceLabels(beat,envelope),literal=exactSource(v,labels),whole=worldSource(envelope).join(" ");const grounding=metric(overlap(meaningful(v),meaningful(labels.join(" ")))*0.75+overlap(meaningful(v),meaningful(whole))*0.25),semantic=semanticAuthorization(v,beat,envelope),invention=metric(concreteRisk(v,whole)),novelty=priorTexts.length?metric(1-Math.max(...priorTexts.map(p=>overlap(meaningful(v),meaningful(p))),0)):1,human=wordCount(v)>=2&&wordCount(v)<=12;const score=literal?metric(0.72+grounding*0.18+novelty*0.1):metric(semantic.authorized?semantic.strength*0.58+grounding*0.15+novelty*0.1+(human?0.07:0)+0.1:0);const reasons:string[]=[];if(literal)reasons.push("literal-source-restatement");if(grounding>=0.24)reasons.push("event-grounded");if(semantic.authorized)reasons.push("approved-semantic-realization");if(semantic.authorized&&!literal)reasons.push("implied-semantic-realization");else if(!literal&&!semantic.authorized)reasons.push("candidate-does-not-express-approved-meaning");if((beat.eventIds??[]).length>1&&grounding>=0.35)reasons.push("cross-event-expression");if(human)reasons.push("human-sized-cut");if(invention>=0.9)reasons.push("unsupported-concrete-risk");return{text:v,beatOrder:beat.order,supportedEventIds:grounding>=0.24&&invention<0.9?[...(beat.eventIds??[])]:[],supportedRelationPairs:(beat.relationKinds??[]).map(String).filter(Boolean),groundingScore:grounding,meaningScore:semantic.authorized?semantic.strength:literal?0.45:0,observerDiscoveryScore:semantic.authorized?Math.max(semantic.strength,0.4):literal?0.12:0,transitionScore:metric(Number(beat.viewerState?.stateShift)||0.4),obligationCoverage:metric(literal?1:semantic.authorized?0.7+semantic.strength*0.3:0),relationContractScore:metric((beat.relationKinds??[]).length?0.85:0.35),forbiddenMoveRisk:invention,cohesionScore:metric(0.55+(semantic.authorized?semantic.strength*0.35:0)+grounding*0.1),noveltyScore:novelty,compressionScore:human?0.95:0.65,inventionRisk:invention,repetitionRisk:1-novelty,collageRisk:0,endpointExactness:literal?1:0,score,reasons}}
function buildSystemPrompt(){return ["You are QRE's ONE MOUTH.","Cognition has already decided the reality, movie, semantic meaning, evidence, relations, viewer movement, and beat order. You only realize approved meaning as language.","Reality freedom is LOW. Framing freedom is HIGH.","Grounding is not authorization. A source word or event ID never authorizes a creative interpretation.","Never invent a person, object, place, physical action, physical relation, reaction, dialogue, event, or chronology.","Use the lens to alter framing, rhythm, irony, tenderness, suspense, status, absurdity, or genre coloration only.","ACCUMULATE: carry forward the significance established by earlier approved beats. A later line may rely on what the viewer has already learned instead of restating it.","IMPLY: communicate an approved relationship through juxtaposition, syntax, contrast, consequence, status, selection, or callback. Do not explain the relationship and do not paraphrase the thesis when implication can carry it.","RECONTEXTUALIZE: let a later approved fact change how an earlier fact is perceived. Preserve the earlier fact; change its significance through the supplied relation.","When several supplied facts participate in one approved semantic turn, make their relationship perceptible instead of captioning each fact independently.","Never write generic atmospheric filler, trailer narration, or a prettier noun for an event.","Do not close every information gap immediately. Build a specific, answerable micro-question when the approved beat supplies one; resolve it at the approved payoff.","At payoff, satisfy the current approved question or tension. Only open another loop when the cognition-supplied next/frontier material supports it; never manufacture a hook for engagement alone.","If no approved semantic realization exists for a beat, use the supplied event literally. Do not invent a meaning.","The goal is felt discovery: the viewer should notice the relationship and arrive at the meaning before the line explains it."].join(" ")}
export function buildMouthCandidateMessages(input:MouthCandidateGenerationInput){const lens=classifyLens(input.lens);return[{role:"system" as const,content:buildSystemPrompt()},{role:"user" as const,content:JSON.stringify({instruction:"Return exactly 3 materially different language realizations for every beat. Accumulate context across the whole sequence. Favor implication and recontextualization over explanation. Each realization should either establish a useful fact, alter the significance of prior approved material, sharpen a supplied unresolved question, or land an approved payoff. When the cognition supplies a next/frontier question, preserve it as a live possibility rather than answering it early.",lens:input.lens||"AUTO",lensProfile:lens,domainContext:input.domainContext??null,reality:worldSource(input.envelope),beats:input.beats.map(b=>({order:b.order,role:b.role,eventIds:b.eventIds??[],evidence:sourceLabels(b,input.envelope),semanticRealization:b.semanticRealization??null,observerExperience:b.observerExperience??null,change:b.change,next:b.next,frontier:b.frontier,obligations:b.obligations??[],forbiddenMoves:b.forbiddenMoves??[]})),priorTexts:input.priorTexts??[],outputSchema:{variantsByBeat:[{order:1,variants:["candidate","candidate","candidate"]}]}},null,2)}]}
export function parseMouthCandidateBatch(raw:string):MouthCandidateBatch|undefined{try{const p=JSON.parse(clean(raw).replace(/^```(?:json)?/i,"").replace(/```$/i,"").trim()) as {variantsByBeat?:unknown};if(!Array.isArray(p.variantsByBeat))return;const variantsByBeat=p.variantsByBeat.map(i=>{const v=i as {order?:unknown;variants?:unknown};return{order:Number(v.order),variants:Array.isArray(v.variants)?v.variants.map(clean).filter(Boolean).slice(0,3):[]}}).filter(i=>Number.isFinite(i.order)&&i.order>0&&i.variants.length>0);return variantsByBeat.length?{variantsByBeat}:undefined}catch{return}}
export function scoreMouthCandidate(input:{text:string;beat:MouthCandidateBeat;envelope:RealityEnvelope;priorTexts?:readonly string[]}):MouthCandidate{return evaluateCandidate(input.text,input.beat,input.envelope,input.priorTexts??[])}
export function isAuthorizedMouthCandidate(candidate:MouthCandidate){if(!clean(candidate.text))return false;if(candidate.inventionRisk>=0.9||candidate.forbiddenMoveRisk>=0.9)return false;if(candidate.endpointExactness>=0.999)return true;return candidate.reasons.includes("approved-semantic-realization")}
function lexicalNovelty(text:string,prior:readonly MouthCandidate[]){if(!prior.length)return 1;const current=meaningful(text);return metric(1-Math.max(...prior.map(c=>overlap(current,meaningful(c.text))),0))}
function pathIncrement(candidate:MouthCandidate,prior:readonly MouthCandidate[],pool:MouthCandidatePool){const s=pool.viewerState,n=lexicalNovelty(candidate.text,prior),carry=prior.length?metric(Math.max(...prior.map(p=>p.meaningScore),0)*0.35+Math.max(...prior.map(p=>p.observerDiscoveryScore),0)*0.25+candidate.meaningScore*0.4):candidate.meaningScore,fit=metric(candidate.transitionScore*0.35+s.stateShift*0.15+s.curiosityPressure*0.2+s.predictionError*0.15+candidate.observerDiscoveryScore*0.15),loop=metric((pool.nextPromise?0.6:0)+(pool.frontier?0.4:0)),bonus=candidate.reasons.includes("approved-semantic-realization")?0.12:0,implicitBonus=candidate.reasons.includes("implied-semantic-realization")?0.06:0,relationBonus=candidate.reasons.includes("cross-event-expression")?0.06:0,penalty=candidate.endpointExactness>=0.999&&!pool.nextPromise&&!pool.frontier?0.08:0;return metric(candidate.score*0.32+fit*0.22+carry*0.14+candidate.meaningScore*0.1+candidate.obligationCoverage*0.05+n*0.05+candidate.cohesionScore*0.04+loop*0.04+bonus+implicitBonus+relationBonus-penalty)}
function dedupe(candidates:readonly MouthCandidate[]){const seen=new Set<string>(),out:MouthCandidate[]=[];for(const c of candidates){const k=clean(c.text).toLowerCase();if(!k||seen.has(k))continue;seen.add(k);out.push(c)}return out}
export function selectBestMouthSequence(pools:readonly MouthCandidatePool[],options:MouthBeamOptions={}):MouthSequencePath{const ordered=[...pools].sort((a,b)=>a.order-b.order);if(!ordered.length)return{candidates:[],texts:[],score:0};if(ordered.some(p=>!p.viewerState||typeof p.viewerState!=="object"))return{candidates:[],texts:[],score:0};const width=Math.max(1,Math.floor(options.width??8));const perBeat=Math.max(1,Math.floor(options.candidatesPerBeat??8));let paths:Array<{candidates:MouthCandidate[];score:number}>=[{candidates:[],score:0}];for(const pool of ordered){let eligible=dedupe(pool.candidates).filter(isAuthorizedMouthCandidate);const creative=eligible.filter(c=>c.reasons.includes("approved-semantic-realization"));if(creative.length)eligible=creative;else eligible=eligible.filter(c=>c.endpointExactness>=0.999);if(!eligible.length)return{candidates:[],texts:[],score:0};eligible.sort((a,b)=>b.score-a.score);eligible=eligible.slice(0,Math.max(width,perBeat));const expanded:Array<{candidates:MouthCandidate[];score:number}>=[];for(const path of paths)for(const candidate of eligible){if(path.candidates.some(p=>clean(p.text).toLowerCase()===clean(candidate.text).toLowerCase()))continue;expanded.push({candidates:[...path.candidates,candidate],score:path.score+pathIncrement(candidate,path.candidates,pool)})}expanded.sort((a,b)=>b.score-a.score);paths=expanded.slice(0,width)}const best=paths[0];if(!best)return{candidates:[],texts:[],score:0};return{candidates:best.candidates,texts:best.candidates.map(c=>c.text),score:metric(best.score/Math.max(1,best.candidates.length))}}
