/**
 * QRE AUTHOR METAMORPHIC RELATION SEARCH
 * --------------------------------------
 *
 * Purpose:
 *   Discover earned changes in meaning between supplied events.
 *
 * This module performs COGNITION only.
 * It does not generate prose and it does not create new reality.
 *
 * Core doctrine:
 *
 *   FACTS
 *      ↓
 *   EVENTS
 *      ↓
 *   RELATIONSHIPS
 *      ↓
 *   METAMORPHIC POSSIBILITY
 *      ↓
 *   SEMANTIC MOVEMENT
 *
 * A metamorphic relation answers:
 *
 *   "What changes in the meaning of supplied reality when these
 *    supplied pieces are considered together?"
 *
 * Hard boundary:
 *   Never invent a concrete event, object, actor, action, location,
 *   chronology, reaction, or outcome.
 *
 * Structural authority:
 *   RealityGraph.relations
 *   RealityGraph.eventStructure
 *   RealityGraph.entityContinuity
 *   RealityGraph.patterns
 *
 * Lexical signals are supporting evidence only.
 * Structural evidence should carry the reasoning whenever available.
 *
 * Function map:
 *
 * clean()
 *   Normalizes arbitrary values into compact strings.
 *
 * metric()
 *   Clamps numeric confidence/score values to the [0, 1] range.
 *
 * unique()
 *   Removes duplicate string identifiers while preserving order.
 *
 * eventLabel()
 *   Resolves the canonical supplied label for an event.
 *
 * structure()
 *   Retrieves the derived structural anatomy for an event.
 *
 * position()
 *   Finds an event's position in the supplied event sequence.
 *
 * hasAny()
 *   Tests a supplied text signal against a lexical pattern.
 *
 * eventFeatures()
 *   Converts one supplied event into normalized structural and
 *   supporting semantic features used by metamorphic reasoning.
 *
 * sameSubject()
 *   Determines whether two events explicitly share an entity.
 *
 * relationCandidate()
 *   Converts an explicit RealityGraph relationship into an earned
 *   metamorphic interpretation.
 *
 * collisionCandidates()
 *   Searches pairs of supplied events for metamorphic collisions
 *   that may exist even when the graph has not emitted an explicit
 *   relation edge.
 *
 * searchMetamorphicRelations()
 *   Orchestrates explicit relationship reasoning first, then pairwise
 *   metamorphic discovery, deduplicates results, enforces candidate
 *   scope, and returns the strongest relations.
 *
 * Pipeline role:
 *
 *   RealityGraph
 *       ↓
 *   searchMetamorphicRelations()
 *       ↓
 *   AuthorMetamorphicRelationSet
 *       ↓
 *   latent story thesis
 *       ↓
 *   movie differentiation
 *       ↓
 *   Mouth realization
 *
 * The metamorphic relation is therefore the semantic bridge between
 * supplied reality and creative realization.
 * DO NOT EDIT THIS FILE UNLESS YOU ARE A QRE CORE DEVELOPER.AND UPDATE THE DOCUMENTATION ABOVE.
 */
import type { LatentSemanticMechanism, RealityGraph, RealityRelation } from "@qre/contracts";

export type MetamorphicRelation = {
  type: string;
  mechanism: LatentSemanticMechanism;
  evidenceEventIds: string[];
  beforeEventIds: string[];
  afterEventIds: string[];
  before: string;
  after: string;
  relation?: { kind: string; fromEventId: string; toEventId: string };
  realizationMove: string;
  creativeOpportunity: string;
  feltEffect: string;
  viewerShift: string;
  languageAim: string;
  confidence: number;
  score: number;
};

const clean = (value: unknown): string => String(value ?? "").replace(/\s+/g, " ").trim();
const metric = (value: number): number => Number(Math.max(0, Math.min(1, Number.isFinite(value) ? value : 0)).toFixed(3));
const unique = (values: readonly string[]): string[] => [...new Set(values.map(clean).filter(Boolean))];

function eventLabel(graph: RealityGraph, id: string): string {
  return clean(graph.events.find((event) => event.id === id)?.label);
}

function structure(graph: RealityGraph, id: string) {
  return graph.eventStructure?.find((item) => item.eventId === id);
}

function position(graph: RealityGraph, id: string): number {
  return graph.events.findIndex((event) => event.id === id);
}

function hasAny(text: string, pattern: RegExp): boolean {
  return pattern.test(text);
}

const PRESENTATION = /\b(clean|cleaned|groomed|bathed|bath|polished|dressed|ready|fresh|finished|beautiful|sharp|dapper|pretty|perfect|special)\b/i;
const MISCHIEF = /\b(stole|stolen|took|taken|snatched|grabbed|lost|ran|escaped|broke|broke into|rebelled|refused|chaos|trouble|mischief|wild|unexpected)\b/i;
const POSITIVE = /\b(happy|proud|calm|excited|confident|comfortable|relieved|good|glad|pleased|delighted|ready|fierce|cool|sharp)\b/i;
const NEGATIVE = /\b(nervous|scared|afraid|anxious|worried|sad|angry|tired|awkward|uneasy|tense|stressed|uncomfortable|lost|broken)\b/i;
const EXPECTED = /\b(unexpected|surprise|surprised|unplanned|did not expect|didn't expect|instead|rather than|but|yet)\b/i;
const RETURN = /\b(again|returned|return|back|still|same|remembered|repeated|later|years?)\b/i;
const OWNERSHIP = /\b(own|owns|owned|stole|stolen|took|taken|kept|had|has|belongs|belonged|gave|received)\b/i;
const SERVICE = /\b(groomed|grooming|bath|bathed|serviced|service|cleaned|clean|tailored|fixed|repaired|washed|polished)\b/i;
const ACTION = /\b(arrived|left|went|came|met|talked|walked|ran|played|danced|called|texted|worked|bought|sold|used|gave|found|lost|stole|took|picked|returned|groomed|grooming|bath|bathed|cleaned|finished|started|stopped|changed|wear|wore|wearing)\b/i;
const OUTCOME = /\b(stole|stolen|took|taken|snatched|grabbed|kept|owned|owns|had|has|belongs|belonged|received|won|finished|left|returned|found|lost|escaped|broke|rebelled|refused|chaos|trouble|mischief|happy|proud|calm|excited|confident|comfortable|relieved|good|glad|pleased|delighted|fierce|cool|sharp|ready|same|still|again|later|wear|wore|wearing|result|outcome|payoff)\b/i;
const OBJECT = /\b(bow|tag|collar|photo|picture|gift|key|keys|ring|flower|flowers|dress|coat|shirt|shoe|shoes|ticket|receipt|book|letter|phone|screen|car|room|house|home|table|door|window|box|bag|cake|towel|towels|leash|tool|tools|food|drink|coffee|music)\b/i;
function eventFeatures(graph: RealityGraph, id: string) {
  const label = eventLabel(graph, id);
  const item = graph.events.find((event) => event.id === id);
  const shape = structure(graph, id);

  const actions = unique([
    ...(shape?.actions ?? []),
  ]);

  const objects = unique([
    ...(shape?.objects ?? []),
  ]);

  const states = unique([
    ...(shape?.states ?? []),
  ]);

  const semanticTags = unique([
    ...(shape?.semanticTags ?? []),
  ]);

  const temporalMarkers = unique([
    ...(shape?.temporalMarkers ?? []),
  ]);

  const sensoryMarkers = unique([
    ...(shape?.sensoryMarkers ?? []),
  ]);

  const text = clean(
    [
      label,
      ...actions,
      ...objects,
      ...states,
      ...semanticTags,
      ...temporalMarkers,
      ...sensoryMarkers,
    ].join(" "),
  );

  const signal = (pattern: RegExp): boolean =>
    pattern.test(text);

  return {
    id,
    label,
    entities: unique(item?.entities ?? shape?.subjects ?? []),

    actions,
    objects,
    states,
    semanticTags,
    temporalMarkers,
    sensoryMarkers,

    action:
      actions.length > 0 ||
      signal(ACTION),

    presentation:
      signal(PRESENTATION),

    mischief:
      signal(MISCHIEF),

    positive:
      signal(POSITIVE),

    negative:
      signal(NEGATIVE),

    expected:
      signal(EXPECTED),

    returnSignal:
      signal(RETURN),

    ownership:
      signal(OWNERSHIP),

    service:
      signal(SERVICE),

    outcome:
      signal(OUTCOME),

    salient:
      item?.salient === true,

    transitionScore:
      metric(shape?.transitionScore ?? 0),

    anomalyScore:
      metric(shape?.anomalyScore ?? 0),

    recurrenceScore:
      metric(shape?.recurrenceScore ?? 0),

    salienceScore:
      metric(
        shape?.salienceScore ??
          (item?.salient ? 1 : 0),
      ),
  };
}
function sameSubject(
  a: ReturnType<typeof eventFeatures>,
  b: ReturnType<typeof eventFeatures>,
): boolean {
  if (!a.entities.length || !b.entities.length) {
    return false;
  }

  const left = new Set(
    a.entities
      .map((value) => clean(value).toLowerCase())
      .filter(Boolean),
  );

  return b.entities.some((value) =>
    left.has(clean(value).toLowerCase()),
  );
}
function relationCandidate(
  graph: RealityGraph,
  relation: RealityRelation,
): MetamorphicRelation | undefined {
  const from = eventLabel(graph, relation.from);
  const to = eventLabel(graph, relation.to);
  if (!from || !to) return undefined;

  const a = eventFeatures(graph, relation.from);
  const b = eventFeatures(graph, relation.to);

  const beforeId = relation.from;
  const afterId = relation.to;
  const before = from;
  const after = to;

  let type = `relation_${relation.kind}`;
  let mechanism: LatentSemanticMechanism = "continuation";
  let realizationMove = "recognize";
  let opportunity = `make ${before} change the reading of ${after}`;
  let felt = "A noticeable change in how the supplied pieces belong together.";
  let shift = `The reading moves from ${before} toward ${after}.`;
  const aim =
    "Let juxtaposition, implication, compression, or reversal carry the relationship.";

  switch (relation.kind) {
    case "contrasts":
      type = "contrast_reversal";
      mechanism = "contrast";
      realizationMove = "hold_contrast";
      opportunity =
        "turn the supplied contrast into a status, attitude, or expectation reversal";
      felt = "A clean jolt between two supplied readings.";
      shift = `The viewer notices the collision between ${before} and ${after}.`;
      break;

    case "causes":
      type = "consequence_reframe";
      mechanism = "consequence";
      realizationMove = "land_consequence";
      opportunity =
        "let the supplied consequence retroactively define the earlier detail";
      felt = "The endpoint suddenly feels earned, ironic, or inevitable.";
      shift = `The viewer reads ${before} differently because ${after} exists.`;
      break;

    case "changes":
      type = "state_to_status";
      mechanism = "state_change";
      realizationMove = "feel_state_transition";
      opportunity =
        "convert a supplied state transition into a change in status, possibility, or attitude";
      felt = "A felt turn: the same subject no longer lands the same way.";
      shift = `The viewer experiences the movement from ${before} to ${after}.`;
      break;

    case "recontextualizes":
      type = "recontextualization";
      mechanism = "recurrence";
      realizationMove = "recontextualize_callback";
      opportunity =
        "make a supplied detail become more significant beside the later detail";
      felt = "Recognition: the earlier detail now means more than it did.";
      shift = "The later detail changes the weight of the earlier one.";
      break;

    case "repeats":
      type = "callback_recontextualization";
      mechanism = "recurrence";
      realizationMove = "recognize_callback";
      opportunity =
        "make the repeated supplied detail carry accumulated meaning instead of merely repeating it";
      felt =
        "A callback lands because the viewer remembers the first occurrence.";
      shift = "The repeated detail returns with a different weight.";
      break;

    case "converges":
      type = "convergence";
      mechanism = "convergence";
      realizationMove = "recognize";
      opportunity =
        "collapse supplied details into one memorable relationship";
      felt = "Separate details suddenly click together.";
      shift = "The viewer sees the supplied pieces as one pattern.";
      break;

    default:
      break;
  }

  const subjectBoost = sameSubject(a, b) ? 0.06 : 0;
  const featureBoost =
    (a.presentation && b.mischief) ||
    (a.service && b.outcome) ||
    (a.negative && b.positive)
      ? 0.12
      : subjectBoost;

  return {
    type,
    mechanism,
    evidenceEventIds: unique([relation.from, relation.to]).sort(),
    beforeEventIds: [beforeId],
    afterEventIds: [afterId],
    before,
    after,
    relation: {
      kind: relation.kind,
      fromEventId: beforeId,
      toEventId: afterId,
    },
    realizationMove,
    creativeOpportunity: opportunity,
    feltEffect: felt,
    viewerShift: shift,
    languageAim: aim,
    confidence: metric(Math.max(0.72, relation.strength + featureBoost)),
    score: metric(relation.strength + featureBoost),
  };
}
function collisionCandidates(
  graph: RealityGraph,
  leftId: string,
  rightId: string,
): MetamorphicRelation[] {
  const left = eventFeatures(graph, leftId);
  const right = eventFeatures(graph, rightId);

  if (!left.label || !right.label) return [];

  const objectOverlap = left.objects.filter((object) =>
    right.objects.includes(object),
  );

  const subjectContinuity = sameSubject(left, right);
  const results: MetamorphicRelation[] = [];

  const push = (
    type: string,
    mechanism: LatentSemanticMechanism,
    beforeId: string,
    afterId: string,
    realizationMove: string,
    creativeOpportunity: string,
    feltEffect: string,
    viewerShift: string,
    languageAim: string,
    confidence: number,
    score: number,
  ) => {
    results.push({
      type,
      mechanism,
      evidenceEventIds: unique([beforeId, afterId]).sort(),
      beforeEventIds: [beforeId],
      afterEventIds: [afterId],
      before: eventLabel(graph, beforeId),
      after: eventLabel(graph, afterId),
      realizationMove,
      creativeOpportunity,
      feltEffect,
      viewerShift,
      languageAim,
      confidence: metric(confidence),
      score: metric(score),
    });
  };

  if (subjectContinuity) {
    if (left.presentation && right.mischief) {
      push(
        "presentation_behavior_collision",
        "contrast",
        leftId,
        rightId,
        "status_reversal",
        "polished presentation becomes the setup for supplied mischief; make the contradiction do the work",
        "A grin-producing contradiction between presentation and behavior.",
        "The polished reading flips into an attitude reading.",
        "Compress the presentation and behavior into one status inversion; never add a new act.",
        0.92,
        0.9,
      );
    } else if (right.presentation && left.mischief) {
      push(
        "presentation_behavior_collision",
        "contrast",
        rightId,
        leftId,
        "status_reversal",
        "polished presentation becomes the setup for supplied mischief; make the contradiction do the work",
        "A grin-producing contradiction between presentation and behavior.",
        "The polished reading flips into an attitude reading.",
        "Compress the presentation and behavior into one status inversion; never add a new act.",
        0.92,
        0.9,
      );
    }

    if (left.service && right.outcome && !right.service) {
      push(
        "service_outcome_inversion",
        "consequence",
        leftId,
        rightId,
        "service_to_status",
        "turn the supplied service into the setup for the supplied result, possession, deviation, state, or return",
        "The service stops feeling like the endpoint and becomes the setup for what the subject actually carries forward.",
        "The viewer reinterprets the service through the supplied outcome.",
        "Make service and outcome collide; do not invent a bridge event or explain the thesis.",
        0.99,
        0.96,
      );
    } else if (right.service && left.outcome && !left.service) {
      push(
        "service_outcome_inversion",
        "consequence",
        rightId,
        leftId,
        "service_to_status",
        "turn the supplied service into the setup for the supplied result, possession, deviation, state, or return",
        "The service stops feeling like the endpoint and becomes the setup for what the subject actually carries forward.",
        "The viewer reinterprets the service through the supplied outcome.",
        "Make service and outcome collide; do not invent a bridge event or explain the thesis.",
        0.99,
        0.96,
      );
    }

    if (left.negative && right.positive) {
      push(
        "state_polarity_turn",
        "state_change",
        leftId,
        rightId,
        "feel_state_transition",
        "let the polarity change become a shift in status or possibility, not an emotional explanation",
        "The viewer feels the turn before it is named.",
        `The supplied reading moves from ${left.label} toward ${right.label}.`,
        "Use contrast or compression; do not explain the emotional thesis.",
        0.91,
        0.89,
      );
    } else if (right.negative && left.positive) {
      push(
        "state_polarity_turn",
        "state_change",
        rightId,
        leftId,
        "feel_state_transition",
        "let the polarity change become a shift in status or possibility, not an emotional explanation",
        "The viewer feels the turn before it is named.",
        `The supplied reading moves from ${right.label} toward ${left.label}.`,
        "Use contrast or compression; do not explain the emotional thesis.",
        0.91,
        0.89,
      );
    }

    if (
      objectOverlap.length &&
      (left.action || right.action) &&
      (left.returnSignal || right.returnSignal)
    ) {
      const object = objectOverlap[0]!;

      push(
        "object_recontextualization",
        "recurrence",
        left.returnSignal ? leftId : rightId,
        left.returnSignal ? rightId : leftId,
        "recognize_callback",
        `make the supplied ${object} return with a changed meaning rather than as a repeated prop`,
        "Recognition plus a new implication for the same supplied detail.",
        `The later ${object} makes the earlier ${object} feel different.`,
        "Let the callback carry the change; do not explain the callback.",
        0.86,
        0.83,
      );
    }

    if (left.expected && right.action) {
      push(
        "expectation_break",
        "contrast",
        leftId,
        rightId,
        "hold_contrast",
        "make the supplied outcome puncture the supplied expectation",
        "A compact surprise without requiring a new plot event.",
        "The expected reading gives way to the supplied result.",
        "Understate the setup and let the supplied outcome supply the punch.",
        0.84,
        0.81,
      );
    } else if (right.expected && left.action) {
      push(
        "expectation_break",
        "contrast",
        rightId,
        leftId,
        "hold_contrast",
        "make the supplied outcome puncture the supplied expectation",
        "A compact surprise without requiring a new plot event.",
        "The expected reading gives way to the supplied result.",
        "Understate the setup and let the supplied outcome supply the punch.",
        0.84,
        0.81,
      );
    }
  }

  return results;
}
export function searchMetamorphicRelations(
  graph: RealityGraph,
  candidateEventIds?: readonly string[],
): MetamorphicRelation[] {
  const graphEventIds = new Set(
    graph.events.map((event) => event.id),
  );

  const ids = unique(
    candidateEventIds ??
      graph.events.map((event) => event.id),
  ).filter(
    (id) =>
      graphEventIds.has(id) &&
      Boolean(eventLabel(graph, id)),
  );

  if (ids.length < 2) return [];

  const scopedIds = new Set(ids);
  const results: MetamorphicRelation[] = [];
  const seen = new Set<string>();

  const add = (result: MetamorphicRelation | undefined) => {
    if (!result) return;

    const evidenceKey = [...result.evidenceEventIds]
      .sort()
      .join(",");

    const key = `${result.type}|${evidenceKey}`;

    if (seen.has(key)) return;

    seen.add(key);
    results.push(result);
  };

  // First consume explicit graph relationships.
  // These are the strongest available evidence because they were
  // already established by the canonical reality graph.
  for (const relation of graph.relations) {
    if (
      relation.kind === "before" ||
      relation.kind === "after" ||
      relation.kind === "involves" ||
      relation.kind === "belongs_to"
    ) {
      continue;
    }

    if (
      !scopedIds.has(relation.from) ||
      !scopedIds.has(relation.to)
    ) {
      continue;
    }

    add(relationCandidate(graph, relation));
  }

  // Then discover metamorphic possibilities between supplied events
  // even when RealityGraph has not explicitly emitted a relation edge.
  for (let i = 0; i < ids.length; i += 1) {
    for (let j = i + 1; j < ids.length; j += 1) {
      const earlierId = ids[i]!;
      const laterId = ids[j]!;

      for (
        const result of collisionCandidates(
          graph,
          earlierId,
          laterId,
        )
      ) {
        add(result);
      }
    }
  }

  return results
    .filter((result) =>
      result.evidenceEventIds.every((id) =>
        scopedIds.has(id),
      ),
    )
    .sort(
      (a, b) =>
        b.score - a.score ||
        b.confidence - a.confidence ||
        a.type.localeCompare(b.type),
    )
    .slice(0, 12);
}