import type { AuthorBrainTruth, AuthorCreativeBrief, AuthorResult, AuthorRhythm, AuthorScene, SequenceCut, SequenceGainKind, SequencePlay, ViewerAttentionRole, ViewerState } from "@qre/contracts";
import { localModelGenerate } from "./localModelRuntime.js";
import { getCreativeLens, rankCreativeLenses, type CreativeLens, type CreativeLensId } from "./authorCreativeLenses.js";

type Operation = "anchor" | "change" | "disruption" | "payoff_setup" | "payoff";
type Candidate = { lens: CreativeLensId; lines: string[] };
type Validation = { ok: boolean; reasons: string[]; score: number };
type ReferencePolicy = { subject: string; mode: "explicit_name"; allowPronouns: false; allowIdentityInference: false; instruction: string };
type CreativeLock = { approvedMeaning: string; transformation: string; lensSearch: CreativeLensId[]; selectedLens: CreativeLensId; lensPrinciple: string; allowedOperations: string[]; allowedFrameTerms: string[]; worldFreedom: "closed"; referencePolicy: ReferencePolicy; payoff: string };
type Directive = { order: number; operation: Operation; source: string; purpose: string; viewerChange: string; realizationGoal: string };
type Packet = { mission: string; subject: string; reality: string[]; intent: string; thesis: string; arc: { baseline: string; change: string; disruption: string; resolution: string; ending: string }; payoff: { target: string; setup: string; requirement: string }; directives: Directive[]; creativeLock: CreativeLock; referencePolicy: ReferencePolicy; style: string[]; output: { lineCount: number; maxWords: number; endingExact: string } };

const MIN_SCORE = 0.76;
const META = /\b(?:as an ai|the audience|the viewer|this means|this shows|the strategy|the beat|according to qre|cognitive)\b/i;
const STOCK = /\b(?:magical moment|unforgettable experience|incredible journey|newfound confidence|a testament to|making memories|cherished moment|one for the books|once in a lifetime|heartwarming)\b/i;
const GLUE = /\b(?:therefore|as a result|which means|this is why|in order to|thus|ultimately)\b/i;
const DECORATION = /\b(?:beautifully|gracefully|dramatically|magically|poetically|gently|softly|wonderfully|incredibly|extremely)\b/i;
const PRONOUN = /\b(?:he|she|him|her|his|hers|they|them|their|theirs)\b/i;
const RELATIONSHIP = /\b(?:husband|wife|partner|girlfriend|boyfriend|sister|brother|mother|father|son|daughter|friend|owner|boss|manager|lawyer|judge|doctor|nurse|employee|customer|officer)\b/i;
const PLACE = /\b(?:street|office|room|chair|table|bed|floor|counter|dresser|park|restaurant|hotel|house|kitchen|bathroom|store|shop|court|church|school|hospital)\b/i;
const BODY = /\b(?:tail|tails|legs|leg|ears|ear|paws|paw|eyes|eye|mouth|teeth|face|head|hands|hand|feet|foot|shoulder|hair|skin)\b/i;
const BODY_IDIOM = /\b(?:in|under|over|on)\s+(?:hand|hands)\b/i;
const STATE = /\b(?:nervous|calm|anxious|confident|quiet|loud|happy|sad|angry|excited|tired|ready|late|early|busy|empty|full|broken|fixed|clean|dirty|fresh|approved|rejected|missing|gone|fabulous|muddy|still|already|finally|peaceful|radiant|unsteady|bold)\b/i;
const ACTION = /\b(?:came|arrived|left|got|stole|found|sent|ordered|changed|ran|returned|noticed|redlined|repaired|disappeared|stayed|moved|laughed|waited|opened|closed|called|signed|checked|cleaned|placed|listed|reviewed|diagnosed|approved|emerged|departed|took)\b/i;

const clean = (value: unknown): string => String(value ?? "").replace(/\s+/g, " ").trim();
const words = (value: string): string[] => clean(value).toLowerCase().split(/[^a-z0-9'-]+/i).filter(Boolean);
const meaningful = (value: string): string[] => words(value).filter((word) => word.length > 2);
const metric = (value: number): number => Number(Math.max(0, Math.min(1, value)).toFixed(3));
const uniq = (values: readonly string[], limit = 48): string[] => [...new Set(values.map(clean).filter(Boolean))].slice(0, limit);

function lineCount(prompt: string): number { const match = clean(prompt).match(/\b(\d{1,2})\s*[- ]?\s*line(?:s)?\b/i); const value = match ? Number(match[1]) : 5; return Number.isFinite(value) ? Math.max(3, Math.min(8, value)) : 5; }
function endpoint(prompt: string): string { const match = clean(prompt).match(/(?:final\s+line|ending|endpoint)\s*:\s*(.+)$/i); return clean(match?.[1] ?? "").replace(/^['\"]|['\"]$/g, ""); }
function reality(input: AuthorBrainTruth): string[] { return uniq([input.subject, input.place ?? "", ...input.facts, ...input.sourceMoments, ...(input.memoryContext ?? []), ...(input.presenceSummary ?? []), ...(input.trajectory ?? [])]); }
function overlap(a: string, b: string): number { const left = new Set(meaningful(a)); const right = new Set(meaningful(b)); if (!left.size || !right.size) return 0; let shared = 0; for (const token of left) if (right.has(token)) shared += 1; return shared / Math.max(left.size, right.size); }
function distinctiveness(value: string, all: string[]): number { const mine = new Set(meaningful(value)); let shared = 0; for (const other of all) { if (other === value) continue; const set = new Set(meaningful(other)); for (const token of mine) if (set.has(token)) shared += 1; } return mine.size / Math.max(1, shared + 1); }
function chooseArc(source: string[], subject: string, ending: string): Packet["arc"] { const material = source.filter((value) => clean(value).toLowerCase() !== subject.toLowerCase()); const baseline = material[0] ?? subject; const change = material[1] ?? material.at(-1) ?? baseline; const middle = material.slice(2, Math.max(2, material.length - 1)); const disruption = [...middle].sort((a, b) => distinctiveness(b, material) - distinctiveness(a, material))[0] ?? material.at(-1) ?? change; const resolution = material.at(-1) ?? change; return { baseline, change, disruption, resolution, ending }; }
function semanticLabel(value: string): string { if (STATE.test(value)) return "state"; if (ACTION.test(value)) return "event"; return "material"; }
function buildReferencePolicy(subject: string): ReferencePolicy { return { subject, mode: "explicit_name", allowPronouns: false, allowIdentityInference: false, instruction: `SUBJECT REFERENCE IS CLOSED. Refer to the subject exactly as "${subject}". Never infer identity or substitute a pronoun.` }; }
function operationFor(index: number, total: number, hasEnding: boolean): Operation { if (index === total - 1) return "payoff"; if (hasEnding && index === total - 2) return "payoff_setup"; if (index === 0) return "anchor"; if (index === 1) return "change"; return "disruption"; }
function realizationGoal(operation: Operation, arc: Packet["arc"], target: string, lens: CreativeLens): string { switch (operation) { case "anchor": return `Establish ${arc.baseline} cleanly.`; case "change": return `Express the changed read created by ${arc.change}; do not copy the fact as a receipt.`; case "disruption": return `Make ${arc.disruption} newly meaningful through the ${lens.id} frame using ${lens.operations.join(", ")}.`; case "payoff_setup": return `Create apparent resolution while keeping pressure alive for ${target}.`; default: return target ? `Land the exact supplied ending as payoff: ${target}.` : "Land the earned consequence and stop."; } }

function buildPacket(input: AuthorBrainTruth): Packet {
  const subject = clean(input.subject) || "the subject"; const intent = clean(input.prompt); const source = reality(input); const ending = endpoint(intent); const count = lineCount(intent); const arc = chooseArc(source, subject, ending); const referencePolicy = buildReferencePolicy(subject); const lensCandidates = rankCreativeLenses(source, ending, input.lens); const selected = lensCandidates[0] ?? getCreativeLens("neutral"); const approvedMeaning = `${subject} moves from ${arc.baseline} through ${arc.change}; ${arc.disruption} becomes newly important, apparent resolution follows, and the final turn recontextualizes what came before.`; const creativeLock: CreativeLock = { approvedMeaning, transformation: "Preserve literal reality. Change the read through an authorized lens; metaphor, status, rhythm, implication, juxtaposition, and attitude may change, but the world remains closed.", lensSearch: lensCandidates.map((lens) => lens.id), selectedLens: selected.id, lensPrinciple: selected.principle, allowedOperations: selected.operations, allowedFrameTerms: selected.frameTerms, worldFreedom: "closed", referencePolicy, payoff: ending || arc.resolution }; const base = { mission: "QRE chooses reality, meaning, lens authorization, progression, and payoff. The model only realizes the locked decision in language.", subject, reality: source, intent, thesis: `${subject}: ${semanticLabel(arc.baseline)} → ${semanticLabel(arc.change)} → ${semanticLabel(arc.disruption)} → apparent resolution → payoff.`, arc, payoff: { target: ending || arc.resolution, setup: ending ? "Build backward from the ending; make the penultimate beat look resolved while preserving pressure." : "Make the final beat the earned consequence.", requirement: ending ? "Exact ending only at the end and it must reframe the sequence." : "Stop on the strongest earned consequence." }, creativeLock, referencePolicy, style: ["Current, direct, compressed language.", "Strong verbs, clean syntax, varied rhythm, implication over explanation.", "The lens should be felt, never announced.", "No AI-summary voice, greeting-card sentiment, corporate mush, generic inspiration, or ornamental filler.", "No new genre entities, props, locations, dialogue, or literal events."], output: { lineCount: count, maxWords: 7, endingExact: ending } };
  const targets = [arc.baseline, arc.change, arc.disruption, arc.resolution, ending || arc.resolution]; const directives: Directive[] = Array.from({ length: count }, (_, index) => { const operation = operationFor(index, count, Boolean(ending)); const sourceTarget = operation === "payoff_setup" ? arc.resolution : operation === "payoff" ? (ending || arc.resolution) : (targets[Math.min(index, targets.length - 1)] ?? subject); return { order: index + 1, operation, source: sourceTarget, purpose: operation, viewerChange: operation === "anchor" ? "baseline established" : operation === "change" ? "meaning changes" : operation === "disruption" ? "new read" : operation === "payoff_setup" ? "resolution appears" : "pressure resolves", realizationGoal: realizationGoal(operation, arc, ending || arc.resolution, selected) }; }); return { ...base, directives }; }

function modelMessage(packet: Packet): Array<{ role: "user"; content: string }> { const lenses = packet.creativeLock.lensSearch.map((id) => getCreativeLens(id)); const candidateCount = lenses.length; const compact = { mission: packet.mission, subject: packet.subject, reality: packet.reality, approvedMeaning: packet.creativeLock.approvedMeaning, transformation: packet.creativeLock.transformation, lenses, directives: packet.directives, payoff: packet.payoff, referencePolicy: packet.referencePolicy, style: packet.style, output: packet.output }; return [{ role: "user", content: ["QRE MOUTH · CREATIVE LOCK.", "QRE already decided reality, meaning, progression, payoff, and the available lenses.", `Return JSON only: {\"candidates\":[{\"lens\":\"id\",\"lines\":[\"...\"]}]}. Produce exactly ${candidateCount} candidates in the supplied lens order.`, `Each candidate has exactly ${packet.output.lineCount} lines; each non-final line is ${packet.output.maxWords} words or fewer.`, packet.output.endingExact ? `Every candidate final line must be EXACTLY: ${packet.output.endingExact}` : "End on the earned consequence.", "A lens is a frame, not permission to create a new world. Preserve supplied facts; transform wording, emphasis, attitude, rhythm, metaphor, implication, status, or juxtaposition only.", packet.referencePolicy.instruction, "No commentary, markdown, explanations, headings, or extra keys.", JSON.stringify(compact)].join("\n") }]; }

function normalizeLine(value: unknown): string { return clean(value).replace(/^(?:[-*•]|\d+[.)])\s*/u, "").replace(/^['\"]|['\"]$/g, "").trim(); }
function parseCandidates(raw: string, count: number, lensIds: CreativeLensId[]): Candidate[] { const text = clean(raw).replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim(); if (!text) return []; try { const parsed = JSON.parse(text) as unknown; if (parsed && typeof parsed === "object") { const record = parsed as Record<string, unknown>; if (Array.isArray(record.candidates)) return record.candidates.map((value, index) => { const item = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { lens: String(item.lens ?? lensIds[index] ?? "neutral") as CreativeLensId, lines: Array.isArray(item.lines) ? item.lines.map(normalizeLine).filter(Boolean) : [] }; }).filter((candidate) => candidate.lines.length === count); if (Array.isArray(record.lines)) return [{ lens: lensIds[0] ?? "neutral", lines: record.lines.map(normalizeLine).filter(Boolean) }].filter((candidate) => candidate.lines.length === count); } } catch { const match = text.match(/\{[\s\S]*\}/); if (match) return parseCandidates(match[0], count, lensIds); } return []; }
function lensTerms(lens: CreativeLens): Set<string> { return new Set(lens.frameTerms.flatMap(meaningful)); }
function worldViolation(line: string, packet: Packet, lens: CreativeLens): string | undefined { const known = packet.reality.join(" ").toLowerCase(); const allowed = lensTerms(lens); for (const [pattern, label] of [[RELATIONSHIP, "relationship"], [PLACE, "place"], [BODY, "body_detail"]] as const) { const match = line.match(pattern); if (!match) continue; const token = match[0].toLowerCase(); if (label === "body_detail" && BODY_IDIOM.test(line)) continue; if (allowed.has(token)) continue; if (!known.includes(token)) return `unsupported_${label}`; } return undefined; }
function exactReplay(line: string, source: string): boolean { const a = clean(line).toLowerCase().replace(/[.!?]+$/g, ""); const b = clean(source).toLowerCase().replace(/[.!?]+$/g, ""); return Boolean(a && b && (a === b || (meaningful(a).length >= 3 && overlap(a, b) >= 0.92))); }
function validate(candidate: Candidate, packet: Packet): Validation { const lens = getCreativeLens(candidate.lens); const reasons: string[] = []; let replay = 0; let transformed = 0; candidate.lines.forEach((line, index) => { const count = words(line).length; if (!count) reasons.push(`line_${index + 1}:empty`); if (index < candidate.lines.length - 1 && count > packet.output.maxWords) reasons.push(`line_${index + 1}:wrong_length`); if (META.test(line)) reasons.push(`line_${index + 1}:meta_language`); if (STOCK.test(line)) reasons.push(`line_${index + 1}:stock_sentiment`); if (GLUE.test(line)) reasons.push(`line_${index + 1}:explanatory_glue`); if (DECORATION.test(line)) reasons.push(`line_${index + 1}:generic_decoration`); if (PRONOUN.test(line)) reasons.push(`line_${index + 1}:unsupported_identity_reference`); const violation = worldViolation(line, packet, lens); if (violation) reasons.push(`line_${index + 1}:${violation}`); if (index > 0 && index < candidate.lines.length - 1) { if (exactReplay(line, packet.directives[index]?.source ?? "")) replay += 1; else transformed += 1; } }); if (replay > 1) reasons.push(`mechanical_fact_replay:${replay}`); if (candidate.lines.length > 3 && transformed < 2) reasons.push("insufficient_creative_transformation"); if (packet.output.endingExact && clean(candidate.lines.at(-1)).toLowerCase() !== packet.output.endingExact.toLowerCase()) reasons.push("endpoint_mismatch"); if (new Set(candidate.lines.map((line) => line.toLowerCase())).size !== candidate.lines.length) reasons.push("duplicate_lines"); const novelty = candidate.lines.length > 1 ? candidate.lines.slice(1).reduce((sum, line, index) => sum + (1 - overlap(line, candidate.lines[index] ?? "")), 0) / (candidate.lines.length - 1) : 0; const transformationRate = candidate.lines.length > 2 ? transformed / Math.max(1, candidate.lines.length - 2) : 1; const lensHits = lens.frameTerms.filter((term) => line.toLowerCase().includes(term.toLowerCase())).length; const lensScore = lens.id === "neutral" ? 0.6 : Math.min(1, 0.5 + lensHits * 0.18); const ending = packet.output.endingExact && clean(candidate.lines.at(-1)).toLowerCase() === packet.output.endingExact.toLowerCase() ? 1 : 0; const score = metric(transformationRate * 0.45 + novelty * 0.18 + ending * 0.24 + lensScore * 0.13); if (score < MIN_SCORE) reasons.push(`quality_below_floor:${score}`); return { ok: reasons.length === 0, reasons, score }; }

function buildSequence(packet: Packet, candidate: Candidate, score: number): SequencePlay { const cuts: SequenceCut[] = []; const known: string[] = []; candidate.lines.forEach((text, index) => { const directive = packet.directives[index]!; const before: ViewerState = { known: [...known], expected: directive.purpose, unresolved: index ? packet.directives[index - 1]?.purpose : undefined, currentWant: directive.viewerChange, recentChange: index ? packet.directives[index - 1]?.source : undefined }; known.push(text); const after: ViewerState = { known: [...known], expected: index === candidate.lines.length - 1 ? undefined : packet.directives[index + 1]?.purpose, unresolved: directive.purpose, currentWant: index === candidate.lines.length - 1 ? undefined : packet.directives[index + 1]?.viewerChange, recentChange: directive.source }; const role: ViewerAttentionRole = index === 0 ? "hook" : index === candidate.lines.length - 1 ? "payoff" : index === candidate.lines.length - 2 ? "reframe" : index === 1 ? "question" : "escalation"; const gainKind: SequenceGainKind = directive.operation === "anchor" ? "baseline" : directive.operation === "change" ? "new_fact" : directive.operation === "disruption" ? "surprise" : directive.operation === "payoff_setup" ? "reframe" : "payoff"; cuts.push({ id: `author-cut-${index + 1}`, order: index + 1, role, gainKind, sourceIds: [`reality:${index + 1}`], informationGain: directive.realizationGoal, attentionDelta: directive.viewerChange, viewerBefore: before, viewerAfter: after, nextPromise: index === candidate.lines.length - 1 ? undefined : packet.directives[index + 1]?.purpose, payoffConnection: index === candidate.lines.length - 1 ? text : packet.output.endingExact || undefined, noveltyScore: metric(index === 0 ? 1 : 1 - overlap(text, candidate.lines[index - 1] ?? "")), confidence: score }); }); return { subject: packet.subject, premise: `${packet.thesis} Lens: ${candidate.lens}.`, openingState: cuts[0]?.viewerBefore ?? { known: [] }, baselineFacts: packet.reality, cuts, closingState: cuts.at(-1)?.viewerAfter, continuity: candidate.lines, antiCrutch: ["no summary", "no explanation", "no unsupported identity inference", "no unsupported world expansion", "no fact parade", "lens is a frame not a world", "ending must be earned", "rejected output never rendered"] }; }
function brief(packet: Packet, lens: CreativeLens): AuthorCreativeBrief { return { angle: packet.creativeLock.approvedMeaning, engine: "reality → meaning → Creative Lock → lens search → one model call → compete → semantic gate", question: packet.output.endingExact ? "What must become newly relevant before the ending lands?" : "What changes next?", strongestImage: packet.arc.disruption || packet.arc.change || packet.arc.baseline, tension: `${packet.arc.baseline} → ${packet.arc.disruption || packet.arc.change}`, payoff: packet.output.endingExact || packet.arc.resolution, callback: `${lens.id}: ${lens.principle}`, rhythm: ["short", "hit", "short", "hit", "short"] as AuthorRhythm[], avoid: ["fact parade", "mechanical replay", "unsupported identity", "unsupported world expansion", "genre-world additions", "detached ending"] }; }

export async function authorBrainUniversal(input: AuthorBrainTruth): Promise<AuthorResult> { const packet = buildPacket(input); const modelResult = await localModelGenerate(modelMessage(packet), "json", { numPredict: Math.min(1100, Math.max(420, packet.output.lineCount * 120 * Math.max(1, packet.creativeLock.lensSearch.length))), temperature: 0.52 }); const candidates = parseCandidates(modelResult.text, packet.output.lineCount, packet.creativeLock.lensSearch); const evaluated = candidates.map((candidate) => ({ candidate, validation: validate(candidate, packet) })).sort((a, b) => b.validation.score - a.validation.score); const winner = evaluated.find((entry) => entry.validation.ok); const raw = process.env.QRE_AUTHOR_DEBUG_RAW === "true" ? modelResult.text : undefined;
  const baseDiagnostics = { model: modelResult.model, modelCalls: 1, candidateSequences: candidates.length, qualityFloor: MIN_SCORE, lineCount: packet.output.lineCount, endpoint: packet.output.endingExact, oneCanonicalPacket: true, thesis: packet.thesis, referencePolicy: packet.referencePolicy, creativeLock: packet.creativeLock, lensCandidates: packet.creativeLock.lensSearch, rejectedOutputNeverRendered: true, rawModelOutput: raw, creativeGrammar: packet.style, payoffContract: packet.payoff };
  if (!winner) return { brief: brief(packet, getCreativeLens(packet.creativeLock.selectedLens)), scenes: [], sequence: undefined, field: { packet, prompt: input.prompt, subject: input.subject }, diagnostics: { ...baseDiagnostics, qualityStatus: "REJECTED_MODEL_OUTPUT", renderable: false, acceptedCandidates: 0, selectedScore: 0, endpointExact: false, complete: false, rejectedCandidates: evaluated.map((entry) => ({ lens: entry.candidate.lens, reasons: entry.validation.reasons, score: entry.validation.score })) } };
  const selected = winner.candidate; const selectedLens = getCreativeLens(selected.lens); const sequence = buildSequence(packet, selected, winner.validation.score); const scenes: AuthorScene[] = selected.lines.map((text, index, all) => ({ text, kind: index === 0 ? "hook" : index === all.length - 1 ? "payoff" : index === all.length - 2 ? "turn" : "movement" }));
  return { brief: brief(packet, selectedLens), scenes, sequence, field: { packet, prompt: input.prompt, subject: input.subject }, diagnostics: { ...baseDiagnostics, qualityStatus: "ACCEPTED", renderable: true, acceptedCandidates: evaluated.filter((entry) => entry.validation.ok).length, selectedScore: winner.validation.score, endpointExact: packet.output.endingExact ? clean(scenes.at(-1)?.text).toLowerCase() === packet.output.endingExact.toLowerCase() : true, complete: true, selectedLens: selected.lens, rejectedCandidates: evaluated.filter((entry) => !entry.validation.ok).map((entry) => ({ lens: entry.candidate.lens, reasons: entry.validation.reasons, score: entry.validation.score })) } };
}
