import { localModelGenerate } from "./localModelRuntime.js";

export type CinematicAuthorInput = {
  prompt: string;
  lens?: string;
  subject?: string;
  place?: string;
  sourceMoments: string[];
  facts: string[];
  memoryContext?: string[];
  creativeLearningContext?: string[];
  trajectory?: string[];
};

export type AuthoredScene = {
  text: string;
  kind?: string;
  durationHintMs?: number;
  transitionHint?: "none" | "fade" | "slide" | "zoom" | "cinematic" | "flash";
  audioMood?: string;
  visualHint?: string;
};

type CreativeIntent = "memory"|"promotion"|"service"|"creator"|"social"|"artist"|"person"|"event"|"artifact"|"story"|"unknown";
type AuthorMode = "concept"|"grounded"|"living_memory"|"service"|"voice_first";
type WorldState = { mode: AuthorMode; timeOfDay: "dawn"|"morning"|"afternoon"|"evening"|"night"|"unknown"; season:"spring"|"summer"|"autumn"|"winter"|"unknown"; date?:string; time?:string; place?:string; suppliedDetails:string[]; creativeAffordances:string[]; hardConstraints:string[] };
type CreativeDirection = { intent:CreativeIntent; mode:AuthorMode; attentionGoal:string; emotionalEngine:string; strongestDetail:string; hiddenPremise:string; sequenceShape:string[]; endingMove:string; targetDensity:"compact"|"standard"|"deep"|"expansive"; selectedOperators:string[]; creativeAffordances:string[]; hardConstraints:string[] };
type SceneDraft={scenes:AuthoredScene[]};
type Critique={score:number;problems:string[];repeats:string[];instructionLeaks:string[];unsupportedDetails:string[];weakScenes:number[];genericLanguage?:string[];weakTransitions?:string[]};

const OPERATORS=["sensory_hook","physical_move","personification","understatement","contrast","micro_reveal","reversal","escalation","status_inversion","zoom_into_detail","callback","tender_turn","comic_turn","mystery_turn","transformation","afterglow","voice","signature"];
const GENERIC=[/picture-perfect/i,/luxury grooming/i,/unforgettable experience/i,/beautiful transformation/i,/magical moment/i,/amazing transformation/i,/as we move/i,/a transformation begins/i,/the experience unfolds/i,/the final reveal/i,/level up/i];
const META=/\b(ai|qre|prompt|compiler|cognition|metadata|model|writing process|instruction)\b/i;
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const uniq=(v:unknown[],n:number)=>[...new Set(v.map(clean).filter(Boolean))].slice(0,n);
const enabled=()=>process.env.QRE_AI_ENABLED==="true"&&process.env.QRE_EXTERNAL_AI_ENABLED!=="true";
function parseJson<T>(text:string):T|null{const s=String(text??"").replace(/^```(?:json)?/i,"").replace(/```$/i,"").trim();try{return JSON.parse(s) as T;}catch{return null;}}
const genericHits=(text:string)=>GENERIC.filter(p=>p.test(text)).length;

function inferIntent(i:CinematicAuthorInput):CreativeIntent{const s=`${i.prompt} ${i.lens??""}`.toLowerCase();const has=(...r:RegExp[])=>r.some(x=>x.test(s));if(has(/\bservice|client|customer|groom|grooming|clean|cleaning|repair|repaired|barber|salon|plumber|mechanic|tattoo|restaurant\b/))return"service";if(has(/\bpromo|promotion|commercial|advert|marketing|sell|selling|business|brand\b/))return"promotion";if(has(/\bcreator|content creator|influencer|youtube|tiktok|reels|shorts|personal brand\b/))return"creator";if(has(/\bsocial|instagram|facebook|threads|post|caption|feed|followers\b/))return"social";if(has(/\bartist|artwork|painting|sculpture|musician|music|song|album|photographer|illustrator|designer|gallery|studio\b/))return"artist";if(has(/\babout me|about myself|my life|my story|my identity|portrait|bio\b/))return"person";if(has(/\bwedding|anniversary|honeymoon|memorial|birthday|family memory|remember|memory\b/))return"memory";if(has(/\bevent|party|festival|ceremony|reunion|conference|opening|show\b/))return"event";if(has(/\bartifact|object|piece|plaque|keychain|sticker|tag|installation|physical art|qr art\b/))return"artifact";if(has(/\bstory|tale|scene|movie|film|fiction|horror|romance\b/))return"story";return"unknown";}
function inferMode(i:CinematicAuthorInput,intent:CreativeIntent):AuthorMode{const evidence=i.facts.length+i.sourceMoments.length+(i.memoryContext?.length??0);if(intent==="service")return evidence?"service":"concept";if(intent==="memory"||intent==="event")return evidence?"living_memory":"concept";if(intent==="creator"||intent==="social"||intent==="artist"||intent==="person")return evidence?"grounded":"voice_first";if(intent==="artifact")return evidence?"grounded":"concept";return evidence?"grounded":"concept";}
function inferTime(text:string):WorldState["timeOfDay"]{const s=text.toLowerCase();if(/\b(12|1|2|3|4|5)\s*(am|a\.m\.)\b/.test(s)||/\b(6|7|8|9|10|11)\s*(pm|p\.m\.)\b/.test(s))return"night";if(/\b(6|7|8|9|10|11)\s*(am|a\.m\.)\b/.test(s))return"morning";if(/\b(12|1|2|3|4|5)\s*(pm|p\.m\.)\b/.test(s))return"afternoon";if(/\bdawn|sunrise\b/.test(s))return"dawn";if(/\bevening|sunset|dusk\b/.test(s))return"evening";return"unknown";}
function inferSeason(text:string):WorldState["season"]{const s=text.toLowerCase();if(/\bdec(?:ember)?|jan(?:uary)?|feb(?:ruary)?\b/.test(s))return"winter";if(/\bmar(?:ch)?|apr(?:il)?|may\b/.test(s))return"spring";if(/\bjun(?:e)?|jul(?:y)?|aug(?:ust)?\b/.test(s))return"summer";if(/\bsep(?:tember)?|oct(?:ober)?|nov(?:ember)?\b/.test(s))return"autumn";return"unknown";}
function affordances(i:CinematicAuthorInput,w:WorldState,intent:CreativeIntent):string[]{const s=[...w.suppliedDetails,i.prompt,i.lens??"",i.place??""].join(" ").toLowerCase();const a:string[]=[];if(w.timeOfDay==="night")a.push("moonlight","reflected light","shoreline lights","night air","quiet surroundings");if(w.timeOfDay==="morning"||w.timeOfDay==="dawn")a.push("early light","waking atmosphere","first movement","fresh start");if(w.timeOfDay==="afternoon")a.push("bright light","active surroundings","heat","visible detail");if(w.timeOfDay==="evening")a.push("fading light","shadows","lights coming on");if(/\bbeach|shore|ocean|sea|coast|water\b/.test(s))a.push("tide","shoreline","water reflection","wind","horizon","distance","sound of water");if(/\bhome|house|room|kitchen|bathroom|living room\b/.test(s))a.push("rooms as characters","traces of activity","objects out of place","before/after contrast");if(intent==="service")a.push("client personality","ritual","small detail","before/after","playful status shift");if(intent==="memory"||intent==="event")a.push("presence","recurrence","meaningful detail","shared meaning","after-image");if(intent==="creator"||intent==="social")a.push("voice","contradiction","obsession","point of view","audience tension","pattern break");if(intent==="artist")a.push("material","texture","signature","visual language","point of view","implied world");if(intent==="person")a.push("habit","contradiction","desire","private detail","relationship","small truth");if(intent==="artifact")a.push("surface detail","touch","ownership","mystery","portal","hidden meaning");return[...new Set(a)].slice(0,14);}
function world(i:CinematicAuthorInput,intent:CreativeIntent):WorldState{const details=uniq([...i.facts,...i.sourceMoments,...(i.memoryContext??[]),i.subject??"",i.place??""],60);const combined=[...details,i.prompt].join(" ");const mode=inferMode(i,intent);const timeOfDay=inferTime(combined);const season=inferSeason(combined);const hard:string[]=[];if(timeOfDay!=="unknown")hard.push(`time_of_day=${timeOfDay}; never contradict this`);if(season!=="unknown")hard.push(`season=${season}; never contradict this`);if(i.place)hard.push(`place=${clean(i.place)}; do not relocate`);if(i.subject)hard.push(`subject=${clean(i.subject)}; do not replace identity`);if(mode!=="concept")hard.push("do not invent concrete events, people, dates, locations, achievements, outcomes, or physical actions as facts");const w:WorldState={mode,timeOfDay,season,date:details.find(x=>/\b20\d{2}\b/.test(x)),time:details.find(x=>/\b\d{1,2}:\d{2}\s*(?:am|pm|a\.m\.|p\.m\.)\b/i.test(x)),place:i.place||details.find(x=>/\b(?:CA|California|NY|New York|Beach|Shore|Street|Ave|Road|Hotel|Gallery|Studio)\b/i.test(x)),suppliedDetails:details,creativeAffordances:[],hardConstraints:hard};w.creativeAffordances=affordances(i,w,intent);return w;}
function fallback(i:CinematicAuthorInput,intent:CreativeIntent,w:WorldState):CreativeDirection{const ops=intent==="service"?["sensory_hook","personification","status_inversion","comic_turn","micro_reveal","transformation","afterglow"]:intent==="creator"||intent==="social"||intent==="artist"?["sensory_hook","voice","zoom_into_detail","micro_reveal","contrast","signature","afterglow"]:intent==="memory"||intent==="event"?["sensory_hook","zoom_into_detail","micro_reveal","callback","tender_turn","reversal","afterglow"]:intent==="artifact"?["sensory_hook","zoom_into_detail","personification","micro_reveal","mystery_turn","afterglow"]:["sensory_hook","physical_move","micro_reveal","contrast","reversal","transformation","afterglow"];return{intent,mode:w.mode,attentionGoal:intent==="service"?"make the ordinary service feel specific, human, and worth watching":"make the viewer stop, feel a point of view, and want the next moment",emotionalEngine:i.lens||(intent==="service"?"personality, contrast, transformation":"curiosity, personality, contrast"),strongestDetail:i.facts[0]||i.sourceMoments[0]||"the prompt's most distinctive idea",hiddenPremise:"Find the hidden relationship, tension, contradiction, game, mystery, or transformation inside the material.",sequenceShape:intent==="memory"||intent==="event"?["arrival","detail","movement","revelation","afterglow"]:["hook","movement","discovery","turn","payoff"],endingMove:"finish on an earned image, reveal, reversal, transformation, or after-image",targetDensity:w.mode==="living_memory"||intent==="person"?"deep":"compact",selectedOperators:ops,creativeAffordances:w.creativeAffordances,hardConstraints:w.hardConstraints};}

async function plan(i:CinematicAuthorInput,f:CreativeDirection,w:WorldState):Promise<CreativeDirection>{if(!enabled())return f;try{const r=await localModelGenerate([{role:"system",content:["You are QRE's senior creative director and cognitive planner.","Do not draft scenes. Find the hidden premise: relationship, tension, contradiction, game, mystery, transformation, or emotional question.","Use the supplied world state and creative affordances.","Reality is hard outside concept mode. In grounded, living_memory, service, and voice_first modes never turn an inferred possibility into a factual event.","Time is authoritative. If the supplied time is 9 PM, think night and exploit night affordances; never write dawn or sunrise unless explicitly supplied.","Place is authoritative.","Sparse concept/voice_first prompts use aspiration, voice, contradiction, desire, tension, or point of view rather than invented biography.","Use sensory image → movement → reveal → reframe/transformation → payoff.","Return strict JSON: intent, mode, attentionGoal, emotionalEngine, strongestDetail, hiddenPremise, sequenceShape, endingMove, targetDensity, selectedOperators.",`OPERATORS: ${OPERATORS.join(", ")}`].join(" ")},{role:"user",content:JSON.stringify({prompt:i.prompt,lens:i.lens??"",subject:i.subject??"",place:i.place??"",facts:uniq(i.facts,40),sourceMoments:uniq(i.sourceMoments,24),memoryContext:uniq(i.memoryContext??[],20),creativeLearningContext:uniq(i.creativeLearningContext??[],20),world:w,fallback:f})}],"json");const p=parseJson<CreativeDirection>(r.text);if(!p?.sequenceShape?.length||!p.attentionGoal)return f;const ops=Array.isArray(p.selectedOperators)?p.selectedOperators.filter(x=>OPERATORS.includes(String(x))).slice(0,7):[];return{...f,...p,mode:w.mode,selectedOperators:ops.length?ops:f.selectedOperators,creativeAffordances:w.creativeAffordances,hardConstraints:w.hardConstraints};}catch{return f;}}
function promptEcho(text:string,prompt:string){const a=clean(text).toLowerCase(),b=clean(prompt).toLowerCase();return a===b||(a.length>30&&b.includes(a));}
function finalize(raw:AuthoredScene[]):AuthoredScene[]{const out:AuthoredScene[]=[];for(const scene of raw){const t=clean(scene.text);if(!t)continue;for(const p of t.split(/(?<=[.!?])\s+(?=[A-Z0-9'"“])/).map(clean).filter(Boolean)){const words=p.split(/\s+/).filter(Boolean);const short=words.length<=18?p:words.slice(0,18).join(" ").replace(/[,:;—-]+$/g,"");if(short)out.push({...scene,text:short});}}return out.slice(0,20).map((s,i,all)=>({...s,kind:s.kind||["hook","movement","discovery","turn","payoff","afterglow"][Math.min(i,5)],durationHintMs:s.durationHintMs??Math.max(1500,Math.min(5000,1100+s.text.split(/\s+/).length*150)),transitionHint:s.transitionHint??(i===0?"none":i===all.length-1?"cinematic":"fade")}));}
function localGate(scenes:AuthoredScene[]){if(scenes.length<3)return false;return scenes.every(s=>s.text.split(/\s+/).length<=18&&genericHits(s.text)===0);}

async function draft(i:CinematicAuthorInput,d:CreativeDirection,w:WorldState):Promise<AuthoredScene[]>{const max=d.targetDensity==="deep"?8:6;const mode=w.mode==="concept"?"CONCEPT: invent cinematic imagery freely, but never invent factual business claims or real-world assertions.":w.mode==="voice_first"?"VOICE-FIRST: build from aspiration, contradiction, desire, obsession, voice and point of view; invent no biography.":"GROUNDED: supplied details define reality. Creative language is allowed; invented concrete events are not.";const r=await localModelGenerate([{role:"system",content:["You are QRE's elite cinematic sequence author.",`Write 3–${max} short viewer-facing scene messages like a miniature film.`,`SHORT IS SWEET PER SCENE. ONE SCENE = ONE THOUGHT = ONE PERCEIVABLE MOMENT.","Prefer 4–14 words; 15–18 only when earned.","Use sensory image → movement → reveal → reframe → payoff.","Every adjacent pair changes the viewer state.","Do not summarize scene one. Do not explain jokes, emotions, metaphors, or endings.","Use attitude; slightly mischievous is welcome.","Avoid generic filler and stock phrasing.",mode,`HIDDEN PREMISE: ${d.hiddenPremise}`,`SEQUENCE: ${d.sequenceShape.join(" → ")}`,`AFFORDANCES: ${w.creativeAffordances.join(" | ")}`,`CONSTRAINTS: ${w.hardConstraints.join(" | ")}`,`OPERATORS: ${d.selectedOperators.join(", ")}`,`ENDING: ${d.endingMove}`,"Return strict JSON only: {\"scenes\":[{\"text\":\"...\",\"kind\":\"hook|movement|discovery|turn|payoff|afterglow\"}]}"].join(" ")},{role:"user",content:JSON.stringify({prompt:i.prompt,lens:i.lens??"",subject:i.subject??"",place:i.place??"",facts:uniq(i.facts,40),sourceMoments:uniq(i.sourceMoments,24),memoryContext:uniq(i.memoryContext??[],20),creativeLearningContext:uniq(i.creativeLearningContext??[],20),world:w})}],"json");const p=parseJson<SceneDraft>(r.text);const raw=Array.isArray(p?.scenes)?p.scenes:[];return finalize(raw.map(s=>({text:clean(s?.text),kind:clean(s?.kind)||"movement"})).filter(s=>s.text&&!META.test(s.text)&&!promptEcho(s.text,i.prompt))).slice(0,max);}

async function critique(i:CinematicAuthorInput,d:CreativeDirection,w:WorldState,s:AuthoredScene[]):Promise<Critique|null>{try{const r=await localModelGenerate([{role:"system",content:["You are QRE's ruthless cinematic editor.","Judge visuality, movement, specificity, forward pull, novelty, short-screen readability, generic language, transitions, payoff, and reality integrity.","In grounded/living_memory/service modes, flag concrete events, actions, people, places, times, or outcomes not supported by the source.","Derived context is allowed only as creative affordance, not factual event.","Return strict JSON: score, problems, repeats, instructionLeaks, unsupportedDetails, weakScenes, genericLanguage, weakTransitions."] .join(" ")},{role:"user",content:JSON.stringify({prompt:i.prompt,direction:d,world:w,facts:uniq(i.facts,40),sourceMoments:uniq(i.sourceMoments,24),scenes:s})}],"json");return parseJson<Critique>(r.text);}catch{return null;}}
async function repair(i:CinematicAuthorInput,d:CreativeDirection,w:WorldState,s:AuthoredScene[],c:Critique):Promise<AuthoredScene[]>{try{const r=await localModelGenerate([{role:"system",content:["You are QRE's elite scene repair editor.","Repair only weak or unsupported beats.","Preserve strong lines and facts.","In grounded/living_memory/service modes remove unsupported concrete events instead of replacing them with other inventions.","Use creative affordances to make the grounded result more vivid.","Keep 4–14 words per scene when possible.","Return strict JSON only: {\"scenes\":[{\"text\":\"...\",\"kind\":\"hook|movement|discovery|turn|payoff|afterglow\"}]}.",`WORLD: ${JSON.stringify(w)}`,`CRITIQUE: ${JSON.stringify(c)}`].join(" ")},{role:"user",content:JSON.stringify({prompt:i.prompt,direction:d,facts:uniq(i.facts,40),sourceMoments:uniq(i.sourceMoments,24),scenes:s})}],"json");const p=parseJson<SceneDraft>(r.text);return finalize((Array.isArray(p?.scenes)?p.scenes:[]).map(x=>({text:clean(x?.text),kind:clean(x?.kind)||"movement"}))).slice(0,20);}catch{return[];}}

export async function authorCinematicSequence(input:CinematicAuthorInput):Promise<AuthoredScene[]>{if(!enabled())return[];const intent=inferIntent(input);const w=world(input,intent);const f=fallback(input,intent,w);const d=await plan(input,f,w);let scenes=await draft(input,d,w);if(scenes.length<3)scenes=await draft(input,d,w);if(scenes.length<3)return[];const c=await critique(input,d,w,scenes);if(c&&(c.score<8||c.problems?.length||c.repeats?.length||c.instructionLeaks?.length||c.unsupportedDetails?.length||c.weakScenes?.length||c.genericLanguage?.length||c.weakTransitions?.length)){const fixed=await repair(input,d,w,scenes,c);if(fixed.length>=3)scenes=fixed;}if(!localGate(scenes)){const fixed=await repair(input,d,w,scenes,{score:7,problems:["local_quality_gate"],repeats:[],instructionLeaks:[],unsupportedDetails:[],weakScenes:[],genericLanguage:[],weakTransitions:[]});if(fixed.length>=3)scenes=fixed;}return scenes;}
