import type { RealityEvent } from "@qre/contracts";

const STOP = new Set(["the","a","an","and","or","but","to","of","in","on","at","for","with","from","by","this","that","it","is","are","was","were","be","been","being","as","into","my","your","our","their","his","her","its","he","she","they","them","you","we","me","again","time","visit","visited","grooming","groomed","place","now","then","first","second","third","would"]);
const STATE = new Set(["happy","sad","angry","calm","excited","nervous","scared","proud","confident","funny","wild","goofy","sweet","gentle","fierce","stubborn","tired","quiet","loud","beautiful","strange","weird","odd","dark","bright","new","old","young","ready","clean","dirty","broken","fixed","alive","gone","back","open","closed","positive","negative","relaxed","anxious","comfortable","uncomfortable"]);
const COLORS = new Set(["red","blue","green","yellow","purple","pink","orange","black","white","brown","gray","grey","silver"]);
const ACTION = new Set(["arrived","arrive","returned","return","came","left","leave","went","go","met","talked","spoke","said","made","gave","got","found","lost","cleaned","finished","started","opened","closed","walked","ran","drove","ate","drank","kissed","married","celebrated","played","worked","visited","bought","sold","built","fixed","painted","wore","used","shook","chewed","connected","stayed","waited","called","laughed","cried","looked","felt","seemed","became","changed","loved","liked","jumped"]);
function normalize(text: string): string { return String(text ?? "").toLowerCase().replace(/[^a-z0-9'’-]+/g, " ").replace(/\s+/g, " ").trim(); }
function tokens(text: string): string[] { return [...new Set(normalize(text).split(" ").filter((token) => token.length >= 3 && !STOP.has(token)))]; }
function shared(a: readonly string[], b: readonly string[]): string[] { const s = new Set(b); return a.filter((x) => s.has(x)); }
function actionTokens(text: string): string[] { return tokens(text).filter((x) => ACTION.has(x)); }
function stateTokens(text: string): string[] { return tokens(text).filter((x) => STATE.has(x)); }
function distinctiveTokens(text: string, context: ReadonlySet<string>): string[] { return tokens(text).filter((x) => !STATE.has(x) && !ACTION.has(x) && !context.has(x)); }
function colorTokens(text: string): string[] { return tokens(text).filter((x) => COLORS.has(x)); }
function contextTokens(prior: readonly string[]): Set<string> { const counts = new Map<string, number>(); for (const anchor of prior) for (const token of new Set(tokens(anchor))) counts.set(token, (counts.get(token) ?? 0) + 1); const threshold = Math.max(2, Math.ceil(prior.length * 0.35)); return new Set([...counts.entries()].filter(([, n]) => n >= threshold).map(([x]) => x)); }
function strength(current: string, prior: string, context: ReadonlySet<string>): number { const states = shared(stateTokens(current), stateTokens(prior)); const distinct = shared(distinctiveTokens(current, context), distinctiveTokens(prior, context)); const colorsA = colorTokens(current), colorsB = colorTokens(prior); const colorReentry = colorsA.length > 0 && colorsB.length > 0 && colorsA.some((x) => !colorsB.includes(x)) && colorsB.some((x) => !colorsA.includes(x)); if (states.length && distinct.length) return 0.98; if (states.length) return 0.9; if (distinct.length >= 2) return 0.86; if (distinct.length === 1 && colorReentry && distinct.some((x) => !COLORS.has(x))) return 0.94; if (distinct.length === 1 && (actionTokens(current).length || actionTokens(prior).length)) return 0.78; return 0; }
export function detectExperienceContinuity(currentEvents: readonly RealityEvent[], priorAnchors: readonly string[]): string[] { if (!currentEvents.length || !priorAnchors.length) return []; const context = contextTokens(priorAnchors); return currentEvents.filter((event) => priorAnchors.some((prior) => strength(event.label, prior, context) >= 0.78)).map((event) => event.id).slice(0,24); }
export function summarizeExperienceContinuity(currentEvents: readonly RealityEvent[], priorAnchors: readonly string[]): string[] { if (!currentEvents.length || !priorAnchors.length) return []; const context = contextTokens(priorAnchors); return currentEvents.flatMap((event) => priorAnchors.map((prior) => ({ prior, strength: strength(event.label, prior, context) })).filter((m) => m.strength >= 0.78).sort((a,b) => b.strength-a.strength).slice(0,2).map((m) => `revisit:${event.id}:${m.prior}`)).slice(0,24); }
