import type { ExperienceState, RealityGraph, RealityRelation, SequenceCandidate } from "@qre/contracts";
const clean=(v:unknown)=>typeof v==="string"?v.replace(/\s+/g," ").trim():"";
const uniq=(xs:string[],n=64)=>[...new Set(xs.filter(Boolean))].slice(0,n);
const metric=(n:number)=>Number.isFinite(n)?Math.max(0,Math.min(1,Number(n.toFixed(3)))):0;
export function buildExperienceState(input:{graph:RealityGraph;candidate:SequenceCandidate;lens?:string;memoryContext?:string[];priorExperienceStates?:ExperienceState[];round?:number}):ExperienceState{
 const previous=input.priorExperienceStates??[];
 const p=(k:keyof ExperienceState)=>uniq(previous.flatMap(s=>{const v=s[k];return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]}));
 const steps=input.candidate.trajectory;
 const used=uniq(steps.flatMap(s=>s.eventIds));
 const relations:RealityRelation[]=input.graph.relations.filter(r=>used.includes(r.from)||used.includes(r.to));
 const active=uniq([...p("activeTensionKeys"),...relations.filter(r=>["contrasts","changes","recontextualizes"].includes(r.kind)).map(r=>`${r.kind}:${r.from}:${r.to}`)]);
 const resolved=uniq([...p("resolvedTensionKeys"),...relations.filter(r=>["causes","converges","repeats"].includes(r.kind)).map(r=>`${r.kind}:${r.from}:${r.to}`)]);
 const changed=uniq([...p("changedEventIds"),...steps.filter(s=>s.operation!=="establish").flatMap(s=>s.eventIds)]);
 const callbacks=uniq([...p("callbackEventIds"),...steps.filter(s=>s.operation==="recur"||s.operation==="reframe").flatMap(s=>s.eventIds)]);
 const continuation=metric(Math.min(1,active.length/4)*.35+Math.min(1,callbacks.length/3)*.2+Math.min(1,previous.length/3)*.2+((input.round??1)>1?.25:0));
 const tempo=active.length>=2?{mode:"tighten" as const,urgency:.8,compression:.72,revealSpacing:.5,holdPressure:.2,nextBeatPull:.82,reason:"Live semantic pressure remains.",arc:["hook","tighten","payoff"]}:{mode:"hold" as const,urgency:.45,compression:.55,revealSpacing:.7,holdPressure:.5,nextBeatPull:.62,reason:"Let the current meaning settle.",arc:["hook","reframe","release"]};
 const future=uniq(input.graph.events.map(e=>e.id).filter(id=>!used.includes(id)),24);
 return {version:1,realityAnchors:uniq([...p("realityAnchors"),...input.graph.events.map(e=>e.label)]),establishedEventIds:uniq([...p("establishedEventIds"),...(steps[0]?.eventIds??[])]),changedEventIds:changed,carrierEventIds:uniq([...p("carrierEventIds"),...used]),activeTensionKeys:active,resolvedTensionKeys:resolved,setupEventIds:uniq([...p("setupEventIds"),...(steps[0]?.eventIds??[])]),callbackEventIds:callbacks,revisitedEventIds:uniq([...p("revisitedEventIds"),...callbacks]),unresolvedQuestions:uniq([...p("unresolvedQuestions"),input.candidate.unresolvedQuestion],16),carryThreads:uniq([...p("carryThreads"),input.candidate.lens,...(input.memoryContext??[])],24),futureEventIds:future,futureThreadKeys:future.map(id=>`future:${id}`),consumedFutureEventIds:p("consumedFutureEventIds"),retiredFutureThreadKeys:p("retiredFutureThreadKeys"),semanticTurnKeys:uniq([...p("semanticTurnKeys"),...relations.map(r=>`${r.kind}:${r.from}:${r.to}`)]),relationKinds:uniq([...p("relationKinds"),...relations.map(r=>r.kind)]),continuationValue:continuation,lookaheadValue:metric(future.length/4),endpointPressure:metric(.2+(steps.filter(s=>s.operation==="payoff").length*.3)),attentionPotential:metric(input.candidate.attentionPotential),tempo,selectedLens:clean(input.lens)||input.candidate.lens,selectedSequenceId:input.candidate.id,payoffEventIds:uniq(steps.filter(s=>s.operation==="payoff").flatMap(s=>s.eventIds)),earnedByEventIds:used,chapter:{openingEventIds:steps[0]?.eventIds??[],finalEventIds:steps.at(-1)?.eventIds??[],semanticTurns:steps.map(s=>s.viewerChange).filter(Boolean),operations:uniq(steps.map(s=>s.operation))},memoryHooks:uniq([...p("memoryHooks"),...callbacks.map(id=>`callback:${id}`),...active.map(x=>`tension:${x}`)],48)};
}
