import "dotenv/config";
import express, { Request, Response } from "express";
import cors from "cors";
import userRouter from "./routes/user.js";
import adminRouter from "./routes/admin.js";
import analyticsRouter from "./routes/analytics.js";
import checkoutRouter from "./routes/checkout.js";
import scanRouter from "./routes/scan.index.js";
import productRouter from "./routes/product.js";
import claimRouter from "./routes/claim.js";
import stripeWebhookRouter from "./routes/stripeWebhook.js";
import stripeTestRouter from "./routes/stripeTest.js";
import dashboardRoutes from "./routes/dashboard.js";
import masterDashboardRoutes from "./routes/masterDashboard.js";
import presenceRoutes from "./routes/presence.js";
import debugRouter from "./routes/debug.js";
import experienceRouter from "./routes/experience.js";
import assetGenerateRouter from "./routes/assets.generate.js";
import geoProofRouter from "./routes/geoProof.js";
import ticketRouter from "./routes/tickets.js";
import quickExperienceRouter from "./routes/quickExperience.js";
import rewardsRouter from "./routes/rewards.js";
import knowledgeRouter from "./routes/knowledge.js";
import learningRouter from "./routes/learning.js";
import stateRouter from "./routes/state.js";
import collectRouter from "./routes/collect.js";
import aiRouter from "./routes/ai.js";
import universalIntakeRouter from "./routes/universalIntake.js";
import contextualExperienceRouter from "./routes/contextualExperience.js";
import { createAnalyticsRepository } from "./repositories/analyticsRepository.js";
import { startAnalyticsSpineSubscriber } from "./services/analyticsSpineSubscriber.js";
import { aiConfigured, aiProviderName } from "./services/aiProvider.js";
import { authRoutes } from "./routes/auth.js";
import { flowRouter } from "./routes/flow.js";
import { requireAuth } from "./middleware/requireAuth.js";
import { presentationBoundary } from "./middleware/presentationBoundary.js";

const app = express();
if (!process.env.JWT_SECRET) throw new Error("JWT_SECRET is missing");
startAnalyticsSpineSubscriber(createAnalyticsRepository());
const corsOrigins = (process.env.CORS_ORIGINS ?? process.env.WEB_ORIGIN ?? "http://localhost:5173").split(",").map((origin) => origin.trim()).filter(Boolean);
app.use(cors({ origin(origin, callback) { if (!origin) return callback(null, true); if (corsOrigins.includes(origin)) return callback(null, true); return callback(new Error("CORS origin denied")); }, credentials: true }));
app.use("/api/stripe/webhook", express.raw({ type: "application/json" }));
app.use(express.json({ limit: "4mb" }));
authRoutes(app);
app.use("/api/assets", requireAuth, assetGenerateRouter);
app.use("/api/user", userRouter);
app.use("/api/admin", adminRouter);
app.use("/api/analytics", analyticsRouter);
app.use("/api/scan", scanRouter);
app.use("/api/checkout", checkoutRouter);
app.use("/api/product", productRouter);
app.use("/api/claim", claimRouter);
app.use("/api/flow", flowRouter);
app.use("/api/presence", presenceRoutes);
app.use("/api/debug", debugRouter);
app.use("/experience", presentationBoundary, experienceRouter);
app.use("/api/contextual-experience", contextualExperienceRouter);
app.use("/api/tickets", ticketRouter);
app.use("/api/quick-experience", quickExperienceRouter);
app.use("/api/rewards", rewardsRouter);
app.use("/api/knowledge", knowledgeRouter);
app.use("/api/learning", learningRouter);
app.use("/api/state", stateRouter);
app.use("/api/collect", collectRouter);
app.use("/api/ai", aiRouter);
app.use("/api/create", universalIntakeRouter);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/dashboard-geoproof", geoProofRouter);
app.use("/api/master-dashboard", masterDashboardRoutes);
app.use("/api/stripe", stripeWebhookRouter);
app.use("/api/stripe", stripeTestRouter);
app.get("/", (_req: Request, res: Response) => res.json({ status: "ok", service: "qre-api", ai: aiConfigured(), provider: aiConfigured() ? aiProviderName() : null }));
const PORT = Number(process.env.PORT || 3000);
app.listen(PORT, () => console.log(`⚡ QRE API running on port ${PORT}`));
