ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AI_CREATIVE_ACCEPTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AI_CREATIVE_REJECTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AI_VARIATION_SELECTED';
