import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import DashboardLayout from "../components/layout/DashboardLayout";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3000";
async function auth(path:string, options:RequestInit={}){const token=localStorage.getItem("token");const r=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}

type Pending={id:string;title?:string|null;prompt:string;contributorName?:string|null;createdAt:string};
export default function CollaborationDashboard(){const{slug}=useParams();const[assetId,setAssetId]=useState("");const[status,setStatus]=useState<any>(null);const[pending,setPending]=useState<Pending[]>([]);const[busy,setBusy]=useState(false);useEffect(()=>{if(!slug)return;getAsset();},[slug]);async function getAsset(){try{const assets=await auth(`/api/assets`);const list=assets.assets??assets;const a=list.find((x:any)=>x.slug===slug);if(!a)return;setAssetId(a.id);const s=await auth(`/experience/collaboration/${a.id}`);setStatus(s);const p=await auth(`/experience/collaboration/${a.id}/pending`);setPending(p.pending??[])}catch(e){console.error(e)}}async function toggle(){if(!assetId||busy)return;setBusy(true);try{const s=await auth(`/experience/collaboration/${assetId}/toggle`,{method:"POST",body:JSON.stringify({enabled:!status?.collaboration?.enabled})});setStatus((v:any)=>({...v,collaboration:s.collaboration}));}finally{setBusy(false)}}async function review(id:string,action:"approve"|"reject"){if(!assetId)return;setBusy(true);try{await auth(`/experience/collaboration/${assetId}/pending/${id}/${action}`,{method:"POST"});setPending((v)=>v.filter((item)=>item.id!==id))}catch(e){console.error(e)}finally{setBusy(false)}}return <DashboardLayout><main style={page}><Link to={`/dashboard/assets/${slug}`} style={back}>BACK</Link><div style={eyebrow}>COLLABORATIVE MEMORY</div><h1 style={title}>Let the world add to it.</h1><p style={body}>People scan your physical QRE art, add a memory, and it waits here until you approve it.</p><section style={card}><div style={row}><div><b>{status?.eligible?"Unlocked":"Locked"}</b><div style={muted}>{status?.plan||""}</div></div><button onClick={()=>void toggle()} disabled={!status?.eligible||busy} style={status?.collaboration?.enabled?buttonOn:button}>{status?.collaboration?.enabled?"TURN OFF":"UNLOCK / TURN ON"}</button></div>{status?.collaboration?.enabled&&<div style={linkBox}>Public add link: <strong>{location.origin}/add/{slug}</strong></div>}</section><section style={card}><h2 style={h2}>Pending memories</h2>{pending.length===0?<p style={muted}>Nothing waiting right now.</p>:pending.map((item)=><article key={item.id} style={itemCard}><div style={eyebrow}>{item.contributorName||"ANONYMOUS"}</div><p style={prompt}>{item.prompt}</p><div style={actions}><button onClick={()=>void review(item.id,"approve")} disabled={busy} style={buttonOn}>APPROVE + MAKE</button><button onClick={()=>void review(item.id,"reject")} disabled={busy} style={button}>REJECT</button></div></article>)}</section></main></DashboardLayout>}
const page={minHeight:"100vh",padding:"70px 24px 100px",color:"#fff",background:"#050608"};const back={color:"rgba(255,255,255,.45)",textDecoration:"none",fontSize:10,letterSpacing:2};const eyebrow={fontSize:9,letterSpacing:4,opacity:.38};const title={fontSize:"clamp(40px,8vw,72px)",fontWeight:500,letterSpacing:"-3px",margin:"18px 0 12px"};const body={maxWidth:620,opacity:.55,lineHeight:1.6};const card={marginTop:28,padding:22,borderRadius:24,border:"1px solid rgba(255,255,255,.08)",background:"rgba(255,255,255,.025)",maxWidth:900};const row={display:"flex",alignItems:"center",justifyContent:"space-between",gap:20};const muted={opacity:.42,fontSize:12,marginTop:5};const h2={fontWeight:500};const button={border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.03)",color:"rgba(255,255,255,.7)",borderRadius:999,padding:"10px 14px",cursor:"pointer",fontSize:10,letterSpacing:1.4};const buttonOn={...button,borderColor:"rgba(185,255,241,.35)",background:"rgba(185,255,241,.12)",color:"#e8fffa"};const linkBox={marginTop:16,padding:12,borderRadius:12,background:"rgba(255,255,255,.03)",fontSize:12,overflowWrap:"anywhere" as const};const itemCard={padding:"18px 0",borderTop:"1px solid rgba(255,255,255,.07)"};const prompt={fontSize:17,lineHeight:1.5,maxWidth:720};const actions={display:"flex",gap:8,flexWrap:"wrap" as const};
