export type HumanStoryBeat = { order:number; text:string; source:string; invented:boolean };
const clean=(value:string)=>value.replace(/\s+/g," ").trim();
function sourceClauses(prompt:string){return clean(prompt).replace(/\s+(?:—|–)\s+/g,". ").split(/(?<=[.!?])\s+|\s*;\s+|\s+(?=(?:then|after that|afterwards|finally|but then|and then)\b)/i).map(clean).filter(Boolean);}
function narrativePrompt(prompt:string){return /\b(?:walked|went|came|entered|returned|chewed|shook|gave|made|finished|found|lost|ran|laughed|cried|opened|closed|left|arrived|called|started|stopped)\b/i.test(prompt)&&!/^(?:make|create|build|turn|write|design|generate)\b/i.test(prompt.trim());}
function connective(i:number,total:number){if(i===1)return "Then ";if(i===total-1)return total>2?"By the end, ":"Then ";return "After that, ";}
function lead(value:string){const text=clean(value);return text?text.charAt(0).toLowerCase()+text.slice(1):text;}
function requestShape(prompt:string){return clean(prompt.replace(/^make\s+(?:this|that)\s+/i,"").replace(/^make\s+(?:a|an|the)\s+/i,"").replace(/^create\s+(?:a|an|the)\s+/i,"").replace(/^build\s+(?:a|an|the)\s+/i,"").replace(/^turn\s+(?:this|that)\s+/i,"").replace(/^write\s+(?:a|an|the)\s+/i,""));}
function nounPhrase(prompt:string){const match=requestShape(prompt).match(/\b(?:dog groomer|housekeeper|birthday|wedding|concert|product launch|spa|scavenger hunt|family recipe|haunted house|watch|artifact|art portal|launch)\b/i);return match?.[0]??"the moment";}
function tone(prompt:string){return prompt.match(/\b(funny|fun|playful|absurd|ridiculous|wild|crazy|terrifying|scary|boring|luxury|romantic|surprising)\b/i)?.[1]?.toLowerCase();}
export function realizeHumanStory(prompt:string):HumanStoryBeat[]{const clauses=sourceClauses(prompt);if(clauses.length>=2&&narrativePrompt(prompt))return clauses.map((clause,i)=>({order:i,text:i===0?clause:connective(i,clauses.length)+lead(clause),source:clause,invented:false}));const subject=nounPhrase(prompt);const requestedTone=tone(prompt);const base=requestShape(prompt);const beats:HumanStoryBeat[]=[{order:0,text:`It starts with ${base.replace(/[.!?]+$/,"")}.`,source:prompt,invented:true}];if(requestedTone)beats.push({order:beats.length,text:requestedTone==="boring"?`The ${subject.toLowerCase()} needs something to happen before anyone cares.`:`The ${subject.toLowerCase()} gets a little ${requestedTone}.`,source:requestedTone,invented:true});beats.push({order:beats.length,text:`That gives ${subject.toLowerCase()} a reason to keep moving.`,source:subject,invented:true});beats.push({order:beats.length,text:`And now there is a moment worth carrying forward.`,source:"causal-closure",invented:true});return beats;}
export function formatHumanStory(prompt:string){return realizeHumanStory(prompt).map(b=>`${b.order+1}. ${b.text}`).join("\n");}
