import type {
  ExperienceEntities, ExperienceGenome, ExperienceMeaning, ExperienceTone,
  ExperienceBlueprint, ExperienceMoment, Moment, CinematicScene, ExperienceModel,
  FlowStep, ExperienceStory, StoryBeat, StoryBeatKind, StoryProvenance,
  StoryScenePlan, SemanticInterpretation,
} from "@qre/contracts";

export type StoryCompilerMemory = { summary: string; entities?: string[]; timestamp?: string };
export type StoryCompilerContext = {
  memories?: StoryCompilerMemory[];
  event?: { name?: string; venue?: string; participants?: string[]; atmosphere?: string; timestamp?: string };
  location?: { label?: string; city?: string; region?: string; country?: string };
};
export type StorySignal = { value: string; source: "prompt"|"context"|"memory"|"event"|"location"; confidence: number; salience: number };
export type StorySituation = { subject:string; actors:string[]; activity:string; setting:string[]; temporal:string[]; social:"solo"|"shared"|"unknown"; purpose:string; change:string; tension:string; signals:StorySignal[] };
type Candidate = { id:string; beats:StoryBeatKind[]; score:number; rationale:string; evidence:StoryProvenance[] };
export type ExperienceObservation = { prompt:string; subject:string; activity:string; context:string[]; entities:ExperienceEntities; explicitEmotions:string[]; audience:string[]; temporal:string[]; affordances:string[]; evidence:StoryProvenance[] };
export type CompiledStoryExperience = { observation:ExperienceObservation; situation:StorySituation; candidates:Candidate[]; genome:ExperienceGenome; story:ExperienceStory; blueprint:ExperienceBlueprint; flowSteps:FlowStep[]; moments:Moment[]; cinematicScenes:CinematicScene[]; scenePlan:StoryScenePlan[]; model:ExperienceModel; title:string; estimatedDuration:number; momentCount:number };

const STOP=new Set(["a","an","the","and","or","but","for","with","about","this","that","into","from","make","create","something","please","experience"]);
const ACTIONS:Array<[RegExp,string]>=[[/\b(groom|grooming|groomer|trim|trimming|bathe|bathing)\b/i,"care"],[/\b(celebrate|celebrating|celebration)\b/i,"celebration"],[/\b(launch|launching|launched)\b/i,"launch"],[/\b(visit|visiting|visited|travel|traveling|trip)\b/i,"movement"],[/\b(meet|meeting|met|connect|connecting)\b/i,"connection"],[/\b(buy|buying|sell|selling|shop|shopping|product)\b/i,"commerce"],[/\b(teach|teaching|learn|learning|lesson|guide)\b/i,"learning"],[/\b(play|playing|game|challenge|quest|race)\b/i,"play"],[/\b(build|building|make|making|create|creating|design|designing)\b/i,"creation"],[/\b(surprise|discover|explore|find|hidden|secret|mystery)\b/i,"discovery"]];
const CONTEXT:Array<[string,RegExp]>=[["event",/\b(event|party|festival|concert|wedding|birthday|crowd|guests?|tonight|ceremony)\b/i],["place",/\b(venue|restaurant|bar|shop|store|home|park|beach|hotel|salon|museum|stadium)\b/i],["memory",/\b(memory|remember|past|history|grandmother|grandfather|childhood|legacy|forever|nostalgia)\b/i],["media",/\b(photo|image|video|film|music|song|voice|recording|qr|nfc|scan)\b/i],["work",/\b(launch|project|meeting|business|office|client|customer|brand|product)\b/i],["play",/\b(fun|funny|playful|wild|game|challenge|quest|surprise)\b/i]];
const EMOTIONS:Array<[RegExp,string]>=[[/\b(fun|funny|playful|joy|happy|delight)\b/i,"joy"],[/\b(love|romantic|beloved)\b/i,"love"],[/\b(excited|excitement|hype|thrill)\b/i,"excitement"],[/\b(calm|peaceful|quiet|gentle)\b/i,"calm"],[/\b(nostalgia|nostalgic|sentimental)\b/i,"nostalgia"],[/\b(mystery|mysterious|secret|hidden|unknown|curious)\b/i,"curiosity"],[/\b(scary|dark|creepy|danger|intense)\b/i,"intensity"]];
const unique=(xs:string[])=>[...new Set(xs.map(x=>x.trim()).filter(Boolean))];
const clean=(x:string)=>x.replace(/\s+/g," ").trim();
const lower=(x:string)=>clean(x).toLowerCase();
const tokens=(x:string)=>clean(x).split(/[^A-Za-z0-9'’-]+/).filter(Boolean);

function entities(prompt:string,c:StoryCompilerContext):ExperienceEntities{const text=clean(prompt),lo=lower(text);const people=unique((text.match(/\b(?:my|for|with|from|by)\s+([A-Z][A-Za-z'’-]+(?:\s+[A-Z][A-Za-z'’-]+){0,2})/g)??[]).map(x=>x.replace(/^\b(?:my|for|with|from|by)\s+/i,"")));const dates=unique(text.match(/\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b/g)??[]);const times=unique(text.match(/\b\d{1,2}(?::\d{2})?\s?(?:am|pm)\b/gi)??[]);const urls=unique(text.match(/https?:\/\/[^\s]+/gi)??[]),emails=unique(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)??[]),phones=unique(text.match(/\+?\d[\d\s().-]{7,}\d/g)??[]);const events=unique(lo.match(/\b(wedding|concert|festival|birthday|party|ceremony|event|show)\b/g)??[]),products=unique(lo.match(/\b(qr|nfc|tag|keychain|sticker|card|poster|shirt|book|product|watch)\b/g)??[]);const places=unique([...c.location?.label?[c.location.label]:[],...(text.match(/\b(?:at|in|near)\s+([A-Z][A-Za-z'’-]+(?:\s+[A-Z][A-Za-z'’-]+){0,3})/g)??[]).map(x=>x.replace(/^\b(?:at|in|near)\s+/i,""))]);const media=/\b(photo|image|video|film|music|song|voice|recording|qr|nfc|scan)\b/i.test(text)?["media"]:[];const keywords=unique(tokens(text).map(x=>x.toLowerCase()).filter(x=>x.length>3&&!STOP.has(x)));return {people,places,organizations:[],dates,times,events,products,urls,phones,media,emails,keywords};}
function subject(prompt:string,e:ExperienceEntities){const direct=prompt.match(/\b(?:for|about|with)\s+([^,.!?]+?)(?:\s+(?:about|at|in|on|tonight|today|now)\b|[,.!?]|$)/i)?.[1],possessive=prompt.match(/\bmy\s+([^,.!?]+?)(?:[,.!?]|$)/i)?.[1];if(direct)return clean(direct);if(possessive)return clean(possessive);return e.people[0]??e.products[0]??e.events[0]??tokens(prompt).filter(x=>!STOP.has(x.toLowerCase())).slice(0,4).join(" ")||"this moment";}
function activity(prompt:string){for(const[p,a]of ACTIONS)if(p.test(prompt))return a;return "observation";}
function contextKinds(prompt:string,c:StoryCompilerContext){const r=CONTEXT.filter(([,p])=>p.test(prompt)).map(([k])=>k);if(c.event)r.push("event");if(c.memories?.length)r.push("memory");if(c.location)r.push("place");return unique(r);}
function emotions(prompt:string){return unique(EMOTIONS.filter(([p])=>p.test(prompt)).map(([,e])=>e));}
function audience(prompt:string,c:StoryCompilerContext){const t=lower(prompt);if(c.event?.participants?.length||/\b(everyone|crowd|guests?|fans?|people|community|group)\b/.test(t))return ["shared"];if(/\b(my|me|mine|personal|private)\b/.test(t))return ["personal"];return ["individual"];}
function temporal(prompt:string,c:StoryCompilerContext){const t=lower(prompt),r:string[]=[];if(/\b(now|today|tonight|live|currently)\b/.test(t))r.push("present");if(/\b(yesterday|last|past|ago|old|formerly)\b/.test(t))r.push("past");if(/\b(tomorrow|next|future|soon|will)\b/.test(t))r.push("future");if(c.event?.timestamp)r.push("event_time");return unique(r);}
function observe(prompt:string,c:StoryCompilerContext):ExperienceObservation{if(!clean(prompt))throw new Error("Experience prompt required.");const e=entities(prompt,c),s=subject(prompt,e),a=activity(prompt),ctx=contextKinds(prompt,c),emo=emotions(prompt),aud=audience(prompt,c),temp=temporal(prompt,c),text=lower(prompt),afford=new Set<string>();if(a!=="observation")afford.add("change");if(aud[0]==="shared")afford.add("connection");if(ctx.length)afford.add("environment");if(c.memories?.length||temp.includes("past"))afford.add("continuity");if(temp.includes("future"))afford.add("anticipation");if(/\b(fun|funny|playful|wild|surprise)\b/.test(text))afford.add("play");if(/\b(mystery|secret|hidden|discover|explore|unknown)\b/.test(text))afford.add("reveal");if(/\b(remember|memory|forever|legacy|preserve|capture)\b/.test(text))afford.add("preservation");if(/\b(boring|ordinary|routine|usual)\b/.test(text))afford.add("contrast");if(/\b(why|meaning|important|significant|matter)\b/.test(text))afford.add("meaning");if(/\b(game|challenge|quest|race|puzzle)\b/.test(text))afford.add("challenge");if(/\b(choice|choose|decide|vote|pick)\b/.test(text))afford.add("choice");if(!afford.size){afford.add("curiosity");afford.add("payoff");}return {prompt:clean(prompt),subject:s,activity:a,context:ctx,entities:e,explicitEmotions:emo,audience:aud,temporal:temp,affordances:[...afford],evidence:[{kind:"observed",source:"prompt",confidence:1}]};}
function situation(o:ExperienceObservation,c:StoryCompilerContext):StorySituation{return {subject:o.subject,actors:unique([...o.entities.people,...(c.event?.participants??[])]),activity:o.activity,setting:unique([...o.context,...(c.event?.venue?[c.event.venue]:[]),...(c.location?.label?[c.location.label]:[])]),temporal:o.temporal,social:o.audience[0]==="shared"?"shared":o.audience[0]==="personal"?"solo":"unknown",purpose:/\b(fun|surprise|story|experience|remember|capture|create|make)\b/i.test(o.prompt)?"create an engaging experience":"make the moment matter",change:o.activity==="observation"?"attention shifts":`${o.activity} changes the situation`,tension:/\b(boring|lost|missing|problem|hard|difficult|danger|unknown|mystery)\b/i.test(o.prompt)?"something needs resolution":"the moment has unrealized potential",signals:o.entities.keywords.slice(0,18).map((v,i)=>({value:v,source:"prompt",confidence:.8,salience:Math.max(.2,1-i/20)}))};}
function tone(o:ExperienceObservation):ExperienceTone[]{const r:ExperienceTone[]=[];if(o.explicitEmotions.includes("joy")||o.affordances.includes("play"))r.push("playful");if(o.explicitEmotions.includes("love")||o.explicitEmotions.includes("nostalgia"))r.push("emotional");if(o.explicitEmotions.includes("excitement"))r.push("energetic");if(o.explicitEmotions.includes("curiosity")||o.affordances.includes("reveal"))r.push("mysterious");if(o.explicitEmotions.includes("intensity"))r.push("dark");return (r.length?r:[o.audience.includes("shared")?"friendly":"cinematic"]) as ExperienceTone[];}
const prov=(kind:StoryProvenance["kind"],source:string,confidence:number):StoryProvenance[]=>[{kind,source,confidence}];
function score(beats:StoryBeatKind[],o:ExperienceObservation,s:StorySituation){const a=new Set(o.affordances),m:Record<StoryBeatKind,string[]>={orientation:["environment","continuity"],hook:["change","contrast","play"],encounter:["connection","environment"],escalation:["challenge","play","connection"],discovery:["reveal","curiosity","meaning"],transformation:["change","contrast"],payoff:["payoff","play"],reflection:["meaning","preservation","continuity"],continuation:["continuity","anticipation","preservation"]};let n=beats.includes("orientation")?1:0;n+=beats.includes("payoff")?1.5:0;for(const b of beats)if(m[b].some(x=>a.has(x)))n+=1.35;if(beats.includes("reflection")&&(o.context.includes("memory")||o.explicitEmotions.length))n+=1.5;if(beats.includes("escalation")&&s.social==="shared")n+=1.2;if(beats.includes("transformation")&&o.activity!=="observation")n+=1.2;if(beats.length>=4&&beats.length<=7)n+=.8;return Number(n.toFixed(3));}
function candidates(o:ExperienceObservation,s:StorySituation):Candidate[]{const raw=[
["momentum",["orientation","hook","escalation","payoff"],"Build energy around what is already happening."],["reveal",["orientation","hook","discovery","payoff"],"Use curiosity to reveal a second layer."],["change",["orientation","hook","transformation","payoff"],"Make visible change the story engine."],["memory",["orientation","encounter","reflection","payoff","continuation"],"Connect present experience to continuity."],["play",["hook","encounter","escalation","payoff"],"Use playful participation as momentum."],["meaning",["orientation","discovery","reflection","payoff"],"Move from surface detail toward significance."],["minimal",["hook","payoff"],"Respect sparse prompts instead of inventing a universe."]
] as Array<[string,StoryBeatKind[],string]>;return raw.map(([id,beats,rationale])=>({id,beats,score:score(beats,o,s),rationale,evidence:prov("inferred",`candidate:${id}`,.7)})).sort((a,b)=>b.score-a.score);}
function choose(cs:Candidate[],o:ExperienceObservation){const bonus=(o.affordances.includes("play")||o.affordances.includes("contrast"))?.35:0;return [...cs].sort((a,b)=>(b.score+(b.id==="play"?bonus:0))-(a.score+(a.id==="play"?bonus:0)))[0];}
function makeBeat(kind:StoryBeatKind,i:number,o:ExperienceObservation,s:StorySituation,t:ExperienceTone):StoryBeat{const subject=o.subject,observed=prov("observed","prompt",1),inferred=prov("inferred","narrative_affordance",.72),playful=prov("playful","story_realizer",.58);const text:Record<StoryBeatKind,string>={orientation:`Start with what is actually here: ${o.prompt}`,hook:`${subject} is not just the subject; the ${s.activity} gives the moment something to move with.`,encounter:`A detail enters the foreground: ${o.entities.keywords.slice(0,3).join(", ")||subject}.`,escalation:s.social==="shared"?`The people around ${subject} add energy, turning a private detail into a shared moment.`:`The moment gathers momentum as ${subject} moves toward possibility.`,discovery:`There is another layer worth noticing: ${o.affordances.includes("reveal")?"something hidden can be revealed":"the ordinary detail starts to mean more than it first appeared to"}.`,transformation:`${subject} moves from the starting condition toward a visibly different state; the change becomes the payoff.`,payoff:t.includes("playful")?`The trick is simple: take what was already there and make it impossible to forget.`:`The moment lands because it stays faithful to what was actually given while making it feel larger.`,reflection:o.explicitEmotions.length?`The experience echoes the feeling already present: ${o.explicitEmotions.join(", ")}.`:`The experience leaves a small question behind: why did this ordinary detail matter?`,continuation:`The story remains open. A return, replay, new memory, or next interaction can add evidence and change what happens next.`};return {id:`beat-${i}-${kind}`,kind,order:i,purpose:`Use ${kind} to advance the experience without forcing a universal shape.`,text:text[kind],entities:unique([subject,...o.entities.keywords.slice(0,3)]),emotionalTarget:t[0]??"curiosity",provenance:kind==="payoff"?[...observed,...playful]:kind==="orientation"?observed:[...observed,...inferred]};}
const cap=(x:string)=>x?x.charAt(0).toUpperCase()+x.slice(1):"The Moment";
function title(subject:string,o:ExperienceObservation,c:Candidate){if(c.id==="play")return `${cap(subject)} Gets Interesting`;if(c.id==="change")return `${cap(subject)} Changes`;if(c.id==="memory")return `${cap(subject)}: Worth Keeping`;if(c.id==="reveal")return `${cap(subject)}: Look Again`;if(o.activity!=="observation")return `${cap(subject)}: ${cap(o.activity)}`;return `${cap(subject)}: The Moment`;}
function story(o:ExperienceObservation,s:StorySituation,c:Candidate,t:ExperienceTone,ctx:StoryCompilerContext):ExperienceStory{const beats=c.beats.map((k,i)=>makeBeat(k,i,o,s,t)),name=title(o.subject.replace(/^the\s+/i,""),o,c),ending=beats.find(b=>b.kind==="payoff")?.text??beats.at(-1)?.text??"The moment continues.";return {title:name,hook:beats[0]?.text??"A moment begins.",logline:`${name} turns ${o.activity} into a variable, evidence-aware experience.${ctx.memories?.length?" Existing memory adds context without replacing the present moment.":""}`,beats,ending,continuation:beats.find(b=>b.kind==="continuation")?.text,tone:t,provenance:[...o.evidence,...c.evidence]};}
function genome(o:ExperienceObservation,st:ExperienceStory):ExperienceGenome{const interpretation:SemanticInterpretation={intent:["experience_creation"],concepts:unique([o.activity,...o.affordances]),emotionalSignals:o.explicitEmotions,worldSignals:o.context,cognitiveSignals:["observation","candidate_search","variable_beats"],confidence:.8};const meaning:ExperienceMeaning={why:st.logline,emotions:o.explicitEmotions,memories:[],desiredFeeling:o.explicitEmotions.length?o.explicitEmotions:["curiosity"],transformation:st.ending};const journey:ExperienceGenome["journey"]=st.beats.flatMap(b=>b.kind==="orientation"?["arrival"]:b.kind==="discovery"?["discovery"]:b.kind==="transformation"?["transformation"]:b.kind==="escalation"?["peak"]:b.kind==="reflection"?["memory"]:b.kind==="continuation"?["return"]:[]);return {intent:["experience_creation"],interpretation,archetypes:[],themes:o.context,emotions:o.explicitEmotions,meaning,relationships:[],energy:st.tone.includes("playful")?"playful":st.tone.includes("energetic")?"intense":st.tone.includes("mysterious")?"mysterious":"emotional",pacing:st.tone.includes("energetic")?"fast":"medium",social:o.audience.includes("shared")?"shared":"solo",journey:unique(journey) as ExperienceGenome["journey"],discovery:(o.affordances.includes("reveal")||o.affordances.includes("curiosity"))?.85:.45,memory:o.context.includes("memory")?.9:0,commerce:o.activity==="commerce"?.8:0,immersion:o.context.includes("media")?.8:.4,interaction:(o.affordances.includes("play")||o.audience.includes("shared"))?.75:.25,replay:(o.context.includes("memory")||o.context.includes("media"))?.8:.25,entities:o.entities,environments:o.context,audience:o.audience,dna:unique(["adaptive","subject-native","evidence-driven","variable-length",...o.affordances])};}
function blueprint(st:ExperienceStory,o:ExperienceObservation):ExperienceBlueprint{const moments:ExperienceMoment[]=st.beats.map(b=>({type:"story",component:"story",title:b.kind==="orientation"?st.title:cap(b.kind),subtitle:b.emotionalTarget,description:b.text,editable:true,demo:false,order:b.order,payload:{beatId:b.id,purpose:b.purpose,entities:b.entities,provenance:b.provenance}}));return {title:st.title,type:"story",tone:st.tone,meaning:{why:st.logline,emotions:o.explicitEmotions,memories:[],desiredFeeling:st.tone,transformation:st.ending},moments,entities:o.entities,metadata:{themes:o.context,dna:["evidence-driven",...o.affordances]}};}
function flow(st:ExperienceStory):FlowStep[]{return st.beats.map(b=>({id:b.id,order:b.order,type:"story",payload:{beat:b}}));}
function moments(st:ExperienceStory):Moment[]{return st.beats.map(b=>({type:"message",order:b.order,text:b.text,meta:{duration:b.kind==="payoff"?2800:2200,beatId:b.id,beatKind:b.kind,emotionalTarget:b.emotionalTarget,entities:b.entities,provenance:b.provenance}}));}
function scenePlan(st:ExperienceStory):StoryScenePlan[]{return st.beats.map(b=>({id:`scene-${b.id}`,order:b.order,beatId:b.id,purpose:b.purpose,text:b.text,emotionalTarget:b.emotionalTarget,entities:b.entities,duration:b.kind==="payoff"?2800:2200,transition:b.kind==="hook"?"zoom":b.kind==="payoff"?"cinematic":"fade",visual:{theme:"cinematic",animation:b.kind==="hook"?"slow_zoom":b.kind==="escalation"?"parallax":"none"},audio:{type:"ambient",mood:b.emotionalTarget},provenance:b.provenance}));}
function scenes(plan:StoryScenePlan[],ms:Moment[]):CinematicScene[]{return plan.map((s,i)=>({id:s.id,type:"emotion",duration:s.duration,moment:ms[i],order:i,transition:s.transition,visual:s.visual,audio:s.audio?{type:s.audio.type,url:"",volume:.7,autoplay:true}:undefined,preload:i<plan.length-1,meta:{source:"story_compiler",purpose:s.purpose,emotionalTarget:s.emotionalTarget,entities:s.entities,provenance:s.provenance}}));}
function model(st:ExperienceStory,b:ExperienceBlueprint):ExperienceModel{return {title:st.title,description:st.logline,industry:"generic",goal:"storytelling",tone:b.tone,moments:b.moments,metadata:{category:"generated_story",tags:["any-prompt","evidence-driven","no-template"]}};}

export function compileStoryExperience(prompt:string,context:StoryCompilerContext={}):CompiledStoryExperience{const o=observe(prompt,context),s=situation(o,context),cs=candidates(o,s),c=choose(cs,o),t=tone(o),st=story(o,s,c,t,context),g=genome(o,st),b=blueprint(st,o),fs=flow(st),ms=moments(st),sp=scenePlan(st),sc=scenes(sp,ms),m=model(st,b);return {observation:o,situation:s,candidates:cs,genome:g,story:st,blueprint:b,flowSteps:fs,moments:ms,cinematicScenes:sc,scenePlan:sp,model:m,title:st.title,estimatedDuration:ms.reduce((n,x)=>n+(x.meta?.duration??2200),0),momentCount:ms.length};}
